// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostUserSearchByNameHandlerFunc turns a function with the right signature into a post user search by name handler
type PostUserSearchByNameHandlerFunc func(PostUserSearchByNameParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUserSearchByNameHandlerFunc) Handle(params PostUserSearchByNameParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostUserSearchByNameHandler interface for that can handle valid post user search by name params
type PostUserSearchByNameHandler interface {
	Handle(PostUserSearchByNameParams, interface{}) middleware.Responder
}

// NewPostUserSearchByName creates a new http.Handler for the post user search by name operation
func NewPostUserSearchByName(ctx *middleware.Context, handler PostUserSearchByNameHandler) *PostUserSearchByName {
	return &PostUserSearchByName{Context: ctx, Handler: handler}
}

/*PostUserSearchByName swagger:route POST /user/search-by-name Users postUserSearchByName

search user by full name and email

*/
type PostUserSearchByName struct {
	Context *middleware.Context
	Handler PostUserSearchByNameHandler
}

func (o *PostUserSearchByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUserSearchByNameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
