// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PutUserUpdateLocaleNoContentCode is the HTTP code returned for type PutUserUpdateLocaleNoContent
const PutUserUpdateLocaleNoContentCode int = 204

/*PutUserUpdateLocaleNoContent success

swagger:response putUserUpdateLocaleNoContent
*/
type PutUserUpdateLocaleNoContent struct {
}

// NewPutUserUpdateLocaleNoContent creates PutUserUpdateLocaleNoContent with default headers values
func NewPutUserUpdateLocaleNoContent() *PutUserUpdateLocaleNoContent {

	return &PutUserUpdateLocaleNoContent{}
}

// WriteResponse to the client
func (o *PutUserUpdateLocaleNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PutUserUpdateLocaleForbiddenCode is the HTTP code returned for type PutUserUpdateLocaleForbidden
const PutUserUpdateLocaleForbiddenCode int = 403

/*PutUserUpdateLocaleForbidden Forbidden

swagger:response putUserUpdateLocaleForbidden
*/
type PutUserUpdateLocaleForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutUserUpdateLocaleForbidden creates PutUserUpdateLocaleForbidden with default headers values
func NewPutUserUpdateLocaleForbidden() *PutUserUpdateLocaleForbidden {

	return &PutUserUpdateLocaleForbidden{}
}

// WithPayload adds the payload to the put user update locale forbidden response
func (o *PutUserUpdateLocaleForbidden) WithPayload(payload *models.Error) *PutUserUpdateLocaleForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user update locale forbidden response
func (o *PutUserUpdateLocaleForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserUpdateLocaleForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutUserUpdateLocaleDefault Unexpected error

swagger:response putUserUpdateLocaleDefault
*/
type PutUserUpdateLocaleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutUserUpdateLocaleDefault creates PutUserUpdateLocaleDefault with default headers values
func NewPutUserUpdateLocaleDefault(code int) *PutUserUpdateLocaleDefault {
	if code <= 0 {
		code = 500
	}

	return &PutUserUpdateLocaleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put user update locale default response
func (o *PutUserUpdateLocaleDefault) WithStatusCode(code int) *PutUserUpdateLocaleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put user update locale default response
func (o *PutUserUpdateLocaleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put user update locale default response
func (o *PutUserUpdateLocaleDefault) WithPayload(payload *models.Error) *PutUserUpdateLocaleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user update locale default response
func (o *PutUserUpdateLocaleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserUpdateLocaleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
