// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "git.softndit.com/collector/backend/models"
)

// NewPutUserUpdateLocaleParams creates a new PutUserUpdateLocaleParams object
// no default values defined in spec.
func NewPutUserUpdateLocaleParams() PutUserUpdateLocaleParams {

	return PutUserUpdateLocaleParams{}
}

// PutUserUpdateLocaleParams contains all the bound params for the put user update locale operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutUserUpdateLocale
type PutUserUpdateLocaleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	RUpdateUserLocale *models.RUpdateUserLocale
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutUserUpdateLocaleParams() beforehand.
func (o *PutUserUpdateLocaleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	var errInterface interface{}

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RUpdateUserLocale
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("rUpdateUserLocale", "body", errInterface))
			} else {
				res = append(res, errors.NewParseError("rUpdateUserLocale", "body", "", err))
			}
		} else {

			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RUpdateUserLocale = &body
			}
		}
	} else {
		res = append(res, errors.Required("rUpdateUserLocale", "body", errInterface))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
