// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteObjectsIDDeleteHandlerFunc turns a function with the right signature into a delete objects ID delete handler
type DeleteObjectsIDDeleteHandlerFunc func(DeleteObjectsIDDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteObjectsIDDeleteHandlerFunc) Handle(params DeleteObjectsIDDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteObjectsIDDeleteHandler interface for that can handle valid delete objects ID delete params
type DeleteObjectsIDDeleteHandler interface {
	Handle(DeleteObjectsIDDeleteParams, interface{}) middleware.Responder
}

// NewDeleteObjectsIDDelete creates a new http.Handler for the delete objects ID delete operation
func NewDeleteObjectsIDDelete(ctx *middleware.Context, handler DeleteObjectsIDDeleteHandler) *DeleteObjectsIDDelete {
	return &DeleteObjectsIDDelete{Context: ctx, Handler: handler}
}

/*DeleteObjectsIDDelete swagger:route DELETE /objects/{ID}/delete Objects deleteObjectsIdDelete

delete object

*/
type DeleteObjectsIDDelete struct {
	Context *middleware.Context
	Handler DeleteObjectsIDDeleteHandler
}

func (o *DeleteObjectsIDDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteObjectsIDDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
