// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// DeleteObjectsIDDeleteNoContentCode is the HTTP code returned for type DeleteObjectsIDDeleteNoContent
const DeleteObjectsIDDeleteNoContentCode int = 204

/*DeleteObjectsIDDeleteNoContent Success

swagger:response deleteObjectsIdDeleteNoContent
*/
type DeleteObjectsIDDeleteNoContent struct {
}

// NewDeleteObjectsIDDeleteNoContent creates DeleteObjectsIDDeleteNoContent with default headers values
func NewDeleteObjectsIDDeleteNoContent() *DeleteObjectsIDDeleteNoContent {

	return &DeleteObjectsIDDeleteNoContent{}
}

// WriteResponse to the client
func (o *DeleteObjectsIDDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteObjectsIDDeleteForbiddenCode is the HTTP code returned for type DeleteObjectsIDDeleteForbidden
const DeleteObjectsIDDeleteForbiddenCode int = 403

/*DeleteObjectsIDDeleteForbidden Forbidden

swagger:response deleteObjectsIdDeleteForbidden
*/
type DeleteObjectsIDDeleteForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteObjectsIDDeleteForbidden creates DeleteObjectsIDDeleteForbidden with default headers values
func NewDeleteObjectsIDDeleteForbidden() *DeleteObjectsIDDeleteForbidden {

	return &DeleteObjectsIDDeleteForbidden{}
}

// WithPayload adds the payload to the delete objects Id delete forbidden response
func (o *DeleteObjectsIDDeleteForbidden) WithPayload(payload *models.Error) *DeleteObjectsIDDeleteForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete objects Id delete forbidden response
func (o *DeleteObjectsIDDeleteForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteObjectsIDDeleteForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteObjectsIDDeleteNotFoundCode is the HTTP code returned for type DeleteObjectsIDDeleteNotFound
const DeleteObjectsIDDeleteNotFoundCode int = 404

/*DeleteObjectsIDDeleteNotFound cant find object

swagger:response deleteObjectsIdDeleteNotFound
*/
type DeleteObjectsIDDeleteNotFound struct {
}

// NewDeleteObjectsIDDeleteNotFound creates DeleteObjectsIDDeleteNotFound with default headers values
func NewDeleteObjectsIDDeleteNotFound() *DeleteObjectsIDDeleteNotFound {

	return &DeleteObjectsIDDeleteNotFound{}
}

// WriteResponse to the client
func (o *DeleteObjectsIDDeleteNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteObjectsIDDeleteLockedCode is the HTTP code returned for type DeleteObjectsIDDeleteLocked
const DeleteObjectsIDDeleteLockedCode int = 423

/*DeleteObjectsIDDeleteLocked Cant delete object

swagger:response deleteObjectsIdDeleteLocked
*/
type DeleteObjectsIDDeleteLocked struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteObjectsIDDeleteLocked creates DeleteObjectsIDDeleteLocked with default headers values
func NewDeleteObjectsIDDeleteLocked() *DeleteObjectsIDDeleteLocked {

	return &DeleteObjectsIDDeleteLocked{}
}

// WithPayload adds the payload to the delete objects Id delete locked response
func (o *DeleteObjectsIDDeleteLocked) WithPayload(payload *models.Error) *DeleteObjectsIDDeleteLocked {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete objects Id delete locked response
func (o *DeleteObjectsIDDeleteLocked) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteObjectsIDDeleteLocked) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(423)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteObjectsIDDeleteDefault Unexpected error

swagger:response deleteObjectsIdDeleteDefault
*/
type DeleteObjectsIDDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteObjectsIDDeleteDefault creates DeleteObjectsIDDeleteDefault with default headers values
func NewDeleteObjectsIDDeleteDefault(code int) *DeleteObjectsIDDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteObjectsIDDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete objects ID delete default response
func (o *DeleteObjectsIDDeleteDefault) WithStatusCode(code int) *DeleteObjectsIDDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete objects ID delete default response
func (o *DeleteObjectsIDDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete objects ID delete default response
func (o *DeleteObjectsIDDeleteDefault) WithPayload(payload *models.Error) *DeleteObjectsIDDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete objects ID delete default response
func (o *DeleteObjectsIDDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteObjectsIDDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
