// Code generated by go-swagger; DO NOT EDIT.

package objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetObjectsIDHandlerFunc turns a function with the right signature into a get objects ID handler
type GetObjectsIDHandlerFunc func(GetObjectsIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetObjectsIDHandlerFunc) Handle(params GetObjectsIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetObjectsIDHandler interface for that can handle valid get objects ID params
type GetObjectsIDHandler interface {
	Handle(GetObjectsIDParams, interface{}) middleware.Responder
}

// NewGetObjectsID creates a new http.Handler for the get objects ID operation
func NewGetObjectsID(ctx *middleware.Context, handler GetObjectsIDHandler) *GetObjectsID {
	return &GetObjectsID{Context: ctx, Handler: handler}
}

/*GetObjectsID swagger:route GET /objects/{ID} Objects getObjectsId

Get object by ID

*/
type GetObjectsID struct {
	Context *middleware.Context
	Handler GetObjectsIDHandler
}

func (o *GetObjectsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetObjectsIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
