// Code generated by go-swagger; DO NOT EDIT.

package materials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteMaterialIDDeleteHandlerFunc turns a function with the right signature into a delete material ID delete handler
type DeleteMaterialIDDeleteHandlerFunc func(DeleteMaterialIDDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteMaterialIDDeleteHandlerFunc) Handle(params DeleteMaterialIDDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteMaterialIDDeleteHandler interface for that can handle valid delete material ID delete params
type DeleteMaterialIDDeleteHandler interface {
	Handle(DeleteMaterialIDDeleteParams, interface{}) middleware.Responder
}

// NewDeleteMaterialIDDelete creates a new http.Handler for the delete material ID delete operation
func NewDeleteMaterialIDDelete(ctx *middleware.Context, handler DeleteMaterialIDDeleteHandler) *DeleteMaterialIDDelete {
	return &DeleteMaterialIDDelete{Context: ctx, Handler: handler}
}

/*DeleteMaterialIDDelete swagger:route DELETE /material/{ID}/delete Materials deleteMaterialIdDelete

DeleteMaterialIDDelete delete material ID delete API

*/
type DeleteMaterialIDDelete struct {
	Context *middleware.Context
	Handler DeleteMaterialIDDeleteHandler
}

func (o *DeleteMaterialIDDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteMaterialIDDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
