// Code generated by go-swagger; DO NOT EDIT.

package materials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetMaterialGetHandlerFunc turns a function with the right signature into a get material get handler
type GetMaterialGetHandlerFunc func(GetMaterialGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMaterialGetHandlerFunc) Handle(params GetMaterialGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetMaterialGetHandler interface for that can handle valid get material get params
type GetMaterialGetHandler interface {
	Handle(GetMaterialGetParams, interface{}) middleware.Responder
}

// NewGetMaterialGet creates a new http.Handler for the get material get operation
func NewGetMaterialGet(ctx *middleware.Context, handler GetMaterialGetHandler) *GetMaterialGet {
	return &GetMaterialGet{Context: ctx, Handler: handler}
}

/*GetMaterialGet swagger:route GET /material/get Materials getMaterialGet

get materials

*/
type GetMaterialGet struct {
	Context *middleware.Context
	Handler GetMaterialGetHandler
}

func (o *GetMaterialGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMaterialGetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
