// Code generated by go-swagger; DO NOT EDIT.

package materials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostMaterialNewOKCode is the HTTP code returned for type PostMaterialNewOK
const PostMaterialNewOKCode int = 200

/*PostMaterialNewOK Success

swagger:response postMaterialNewOK
*/
type PostMaterialNewOK struct {

	/*
	  In: Body
	*/
	Payload *models.ACreateMaterial `json:"body,omitempty"`
}

// NewPostMaterialNewOK creates PostMaterialNewOK with default headers values
func NewPostMaterialNewOK() *PostMaterialNewOK {

	return &PostMaterialNewOK{}
}

// WithPayload adds the payload to the post material new o k response
func (o *PostMaterialNewOK) WithPayload(payload *models.ACreateMaterial) *PostMaterialNewOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post material new o k response
func (o *PostMaterialNewOK) SetPayload(payload *models.ACreateMaterial) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostMaterialNewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostMaterialNewForbiddenCode is the HTTP code returned for type PostMaterialNewForbidden
const PostMaterialNewForbiddenCode int = 403

/*PostMaterialNewForbidden access forbidden

swagger:response postMaterialNewForbidden
*/
type PostMaterialNewForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostMaterialNewForbidden creates PostMaterialNewForbidden with default headers values
func NewPostMaterialNewForbidden() *PostMaterialNewForbidden {

	return &PostMaterialNewForbidden{}
}

// WithPayload adds the payload to the post material new forbidden response
func (o *PostMaterialNewForbidden) WithPayload(payload *models.Error) *PostMaterialNewForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post material new forbidden response
func (o *PostMaterialNewForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostMaterialNewForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostMaterialNewConflictCode is the HTTP code returned for type PostMaterialNewConflict
const PostMaterialNewConflictCode int = 409

/*PostMaterialNewConflict material already present

swagger:response postMaterialNewConflict
*/
type PostMaterialNewConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostMaterialNewConflict creates PostMaterialNewConflict with default headers values
func NewPostMaterialNewConflict() *PostMaterialNewConflict {

	return &PostMaterialNewConflict{}
}

// WithPayload adds the payload to the post material new conflict response
func (o *PostMaterialNewConflict) WithPayload(payload *models.Error) *PostMaterialNewConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post material new conflict response
func (o *PostMaterialNewConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostMaterialNewConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostMaterialNewDefault Unexpected error

swagger:response postMaterialNewDefault
*/
type PostMaterialNewDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostMaterialNewDefault creates PostMaterialNewDefault with default headers values
func NewPostMaterialNewDefault(code int) *PostMaterialNewDefault {
	if code <= 0 {
		code = 500
	}

	return &PostMaterialNewDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post material new default response
func (o *PostMaterialNewDefault) WithStatusCode(code int) *PostMaterialNewDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post material new default response
func (o *PostMaterialNewDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post material new default response
func (o *PostMaterialNewDefault) WithPayload(payload *models.Error) *PostMaterialNewDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post material new default response
func (o *PostMaterialNewDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostMaterialNewDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
