// Code generated by go-swagger; DO NOT EDIT.

package nameddateintervals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetNamedDateIntervalGetHandlerFunc turns a function with the right signature into a get named date interval get handler
type GetNamedDateIntervalGetHandlerFunc func(GetNamedDateIntervalGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNamedDateIntervalGetHandlerFunc) Handle(params GetNamedDateIntervalGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetNamedDateIntervalGetHandler interface for that can handle valid get named date interval get params
type GetNamedDateIntervalGetHandler interface {
	Handle(GetNamedDateIntervalGetParams, interface{}) middleware.Responder
}

// NewGetNamedDateIntervalGet creates a new http.Handler for the get named date interval get operation
func NewGetNamedDateIntervalGet(ctx *middleware.Context, handler GetNamedDateIntervalGetHandler) *GetNamedDateIntervalGet {
	return &GetNamedDateIntervalGet{Context: ctx, Handler: handler}
}

/*GetNamedDateIntervalGet swagger:route GET /named-date-interval/get Nameddateintervals getNamedDateIntervalGet

get named date intervals

*/
type GetNamedDateIntervalGet struct {
	Context *middleware.Context
	Handler GetNamedDateIntervalGetHandler
}

func (o *GetNamedDateIntervalGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetNamedDateIntervalGetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
