// Code generated by go-swagger; DO NOT EDIT.

package nameddateintervals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostNamedDateIntervalIDUpdateHandlerFunc turns a function with the right signature into a post named date interval ID update handler
type PostNamedDateIntervalIDUpdateHandlerFunc func(PostNamedDateIntervalIDUpdateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostNamedDateIntervalIDUpdateHandlerFunc) Handle(params PostNamedDateIntervalIDUpdateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostNamedDateIntervalIDUpdateHandler interface for that can handle valid post named date interval ID update params
type PostNamedDateIntervalIDUpdateHandler interface {
	Handle(PostNamedDateIntervalIDUpdateParams, interface{}) middleware.Responder
}

// NewPostNamedDateIntervalIDUpdate creates a new http.Handler for the post named date interval ID update operation
func NewPostNamedDateIntervalIDUpdate(ctx *middleware.Context, handler PostNamedDateIntervalIDUpdateHandler) *PostNamedDateIntervalIDUpdate {
	return &PostNamedDateIntervalIDUpdate{Context: ctx, Handler: handler}
}

/*PostNamedDateIntervalIDUpdate swagger:route POST /named-date-interval/{ID}/update Nameddateintervals postNamedDateIntervalIdUpdate

update named date interval

*/
type PostNamedDateIntervalIDUpdate struct {
	Context *middleware.Context
	Handler PostNamedDateIntervalIDUpdateHandler
}

func (o *PostNamedDateIntervalIDUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostNamedDateIntervalIDUpdateParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
