// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostCollectionsObjectsOKCode is the HTTP code returned for type PostCollectionsObjectsOK
const PostCollectionsObjectsOKCode int = 200

/*PostCollectionsObjectsOK Collection objects list

swagger:response postCollectionsObjectsOK
*/
type PostCollectionsObjectsOK struct {

	/*
	  In: Body
	*/
	Payload *models.AObjectsPreview `json:"body,omitempty"`
}

// NewPostCollectionsObjectsOK creates PostCollectionsObjectsOK with default headers values
func NewPostCollectionsObjectsOK() *PostCollectionsObjectsOK {

	return &PostCollectionsObjectsOK{}
}

// WithPayload adds the payload to the post collections objects o k response
func (o *PostCollectionsObjectsOK) WithPayload(payload *models.AObjectsPreview) *PostCollectionsObjectsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections objects o k response
func (o *PostCollectionsObjectsOK) SetPayload(payload *models.AObjectsPreview) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsObjectsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCollectionsObjectsForbiddenCode is the HTTP code returned for type PostCollectionsObjectsForbidden
const PostCollectionsObjectsForbiddenCode int = 403

/*PostCollectionsObjectsForbidden Forbidden

swagger:response postCollectionsObjectsForbidden
*/
type PostCollectionsObjectsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCollectionsObjectsForbidden creates PostCollectionsObjectsForbidden with default headers values
func NewPostCollectionsObjectsForbidden() *PostCollectionsObjectsForbidden {

	return &PostCollectionsObjectsForbidden{}
}

// WithPayload adds the payload to the post collections objects forbidden response
func (o *PostCollectionsObjectsForbidden) WithPayload(payload *models.Error) *PostCollectionsObjectsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections objects forbidden response
func (o *PostCollectionsObjectsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsObjectsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostCollectionsObjectsDefault Unexpected error

swagger:response postCollectionsObjectsDefault
*/
type PostCollectionsObjectsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCollectionsObjectsDefault creates PostCollectionsObjectsDefault with default headers values
func NewPostCollectionsObjectsDefault(code int) *PostCollectionsObjectsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostCollectionsObjectsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post collections objects default response
func (o *PostCollectionsObjectsDefault) WithStatusCode(code int) *PostCollectionsObjectsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post collections objects default response
func (o *PostCollectionsObjectsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post collections objects default response
func (o *PostCollectionsObjectsDefault) WithPayload(payload *models.Error) *PostCollectionsObjectsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections objects default response
func (o *PostCollectionsObjectsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsObjectsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
