// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostCollectionsAddToGroupHandlerFunc turns a function with the right signature into a post collections add to group handler
type PostCollectionsAddToGroupHandlerFunc func(PostCollectionsAddToGroupParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCollectionsAddToGroupHandlerFunc) Handle(params PostCollectionsAddToGroupParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostCollectionsAddToGroupHandler interface for that can handle valid post collections add to group params
type PostCollectionsAddToGroupHandler interface {
	Handle(PostCollectionsAddToGroupParams, interface{}) middleware.Responder
}

// NewPostCollectionsAddToGroup creates a new http.Handler for the post collections add to group operation
func NewPostCollectionsAddToGroup(ctx *middleware.Context, handler PostCollectionsAddToGroupHandler) *PostCollectionsAddToGroup {
	return &PostCollectionsAddToGroup{Context: ctx, Handler: handler}
}

/*PostCollectionsAddToGroup swagger:route POST /collections/add-to-group Collections postCollectionsAddToGroup

add collections to group

*/
type PostCollectionsAddToGroup struct {
	Context *middleware.Context
	Handler PostCollectionsAddToGroupHandler
}

func (o *PostCollectionsAddToGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostCollectionsAddToGroupParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
