// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostCollectionsOKCode is the HTTP code returned for type PostCollectionsOK
const PostCollectionsOKCode int = 200

/*PostCollectionsOK success

swagger:response postCollectionsOK
*/
type PostCollectionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ANewCollection `json:"body,omitempty"`
}

// NewPostCollectionsOK creates PostCollectionsOK with default headers values
func NewPostCollectionsOK() *PostCollectionsOK {

	return &PostCollectionsOK{}
}

// WithPayload adds the payload to the post collections o k response
func (o *PostCollectionsOK) WithPayload(payload *models.ANewCollection) *PostCollectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections o k response
func (o *PostCollectionsOK) SetPayload(payload *models.ANewCollection) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCollectionsForbiddenCode is the HTTP code returned for type PostCollectionsForbidden
const PostCollectionsForbiddenCode int = 403

/*PostCollectionsForbidden Forbidden

swagger:response postCollectionsForbidden
*/
type PostCollectionsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCollectionsForbidden creates PostCollectionsForbidden with default headers values
func NewPostCollectionsForbidden() *PostCollectionsForbidden {

	return &PostCollectionsForbidden{}
}

// WithPayload adds the payload to the post collections forbidden response
func (o *PostCollectionsForbidden) WithPayload(payload *models.Error) *PostCollectionsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections forbidden response
func (o *PostCollectionsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCollectionsUnprocessableEntityCode is the HTTP code returned for type PostCollectionsUnprocessableEntity
const PostCollectionsUnprocessableEntityCode int = 422

/*PostCollectionsUnprocessableEntity unprocessable input

swagger:response postCollectionsUnprocessableEntity
*/
type PostCollectionsUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCollectionsUnprocessableEntity creates PostCollectionsUnprocessableEntity with default headers values
func NewPostCollectionsUnprocessableEntity() *PostCollectionsUnprocessableEntity {

	return &PostCollectionsUnprocessableEntity{}
}

// WithPayload adds the payload to the post collections unprocessable entity response
func (o *PostCollectionsUnprocessableEntity) WithPayload(payload *models.Error) *PostCollectionsUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections unprocessable entity response
func (o *PostCollectionsUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostCollectionsDefault Unexpected error

swagger:response postCollectionsDefault
*/
type PostCollectionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCollectionsDefault creates PostCollectionsDefault with default headers values
func NewPostCollectionsDefault(code int) *PostCollectionsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostCollectionsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post collections default response
func (o *PostCollectionsDefault) WithStatusCode(code int) *PostCollectionsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post collections default response
func (o *PostCollectionsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post collections default response
func (o *PostCollectionsDefault) WithPayload(payload *models.Error) *PostCollectionsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post collections default response
func (o *PostCollectionsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCollectionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
