// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// GetGroupsIDOKCode is the HTTP code returned for type GetGroupsIDOK
const GetGroupsIDOKCode int = 200

/*GetGroupsIDOK Group collections list

swagger:response getGroupsIdOK
*/
type GetGroupsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.AGroup `json:"body,omitempty"`
}

// NewGetGroupsIDOK creates GetGroupsIDOK with default headers values
func NewGetGroupsIDOK() *GetGroupsIDOK {

	return &GetGroupsIDOK{}
}

// WithPayload adds the payload to the get groups Id o k response
func (o *GetGroupsIDOK) WithPayload(payload *models.AGroup) *GetGroupsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get groups Id o k response
func (o *GetGroupsIDOK) SetPayload(payload *models.AGroup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupsIDForbiddenCode is the HTTP code returned for type GetGroupsIDForbidden
const GetGroupsIDForbiddenCode int = 403

/*GetGroupsIDForbidden Forbidden

swagger:response getGroupsIdForbidden
*/
type GetGroupsIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetGroupsIDForbidden creates GetGroupsIDForbidden with default headers values
func NewGetGroupsIDForbidden() *GetGroupsIDForbidden {

	return &GetGroupsIDForbidden{}
}

// WithPayload adds the payload to the get groups Id forbidden response
func (o *GetGroupsIDForbidden) WithPayload(payload *models.Error) *GetGroupsIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get groups Id forbidden response
func (o *GetGroupsIDForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetGroupsIDDefault Unexpected error

swagger:response getGroupsIdDefault
*/
type GetGroupsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetGroupsIDDefault creates GetGroupsIDDefault with default headers values
func NewGetGroupsIDDefault(code int) *GetGroupsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetGroupsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get groups ID default response
func (o *GetGroupsIDDefault) WithStatusCode(code int) *GetGroupsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get groups ID default response
func (o *GetGroupsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get groups ID default response
func (o *GetGroupsIDDefault) WithPayload(payload *models.Error) *GetGroupsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get groups ID default response
func (o *GetGroupsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
