// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostAuthPasswordResetTokenNoContentCode is the HTTP code returned for type PostAuthPasswordResetTokenNoContent
const PostAuthPasswordResetTokenNoContentCode int = 204

/*PostAuthPasswordResetTokenNoContent Password has been updated

swagger:response postAuthPasswordResetTokenNoContent
*/
type PostAuthPasswordResetTokenNoContent struct {
}

// NewPostAuthPasswordResetTokenNoContent creates PostAuthPasswordResetTokenNoContent with default headers values
func NewPostAuthPasswordResetTokenNoContent() *PostAuthPasswordResetTokenNoContent {

	return &PostAuthPasswordResetTokenNoContent{}
}

// WriteResponse to the client
func (o *PostAuthPasswordResetTokenNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*PostAuthPasswordResetTokenDefault Unexpected error

swagger:response postAuthPasswordResetTokenDefault
*/
type PostAuthPasswordResetTokenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthPasswordResetTokenDefault creates PostAuthPasswordResetTokenDefault with default headers values
func NewPostAuthPasswordResetTokenDefault(code int) *PostAuthPasswordResetTokenDefault {
	if code <= 0 {
		code = 500
	}

	return &PostAuthPasswordResetTokenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post auth password reset token default response
func (o *PostAuthPasswordResetTokenDefault) WithStatusCode(code int) *PostAuthPasswordResetTokenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post auth password reset token default response
func (o *PostAuthPasswordResetTokenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post auth password reset token default response
func (o *PostAuthPasswordResetTokenDefault) WithPayload(payload *models.Error) *PostAuthPasswordResetTokenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth password reset token default response
func (o *PostAuthPasswordResetTokenDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthPasswordResetTokenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
