// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostAuthRegNoContentCode is the HTTP code returned for type PostAuthRegNoContent
const PostAuthRegNoContentCode int = 204

/*PostAuthRegNoContent Cinfirm email

swagger:response postAuthRegNoContent
*/
type PostAuthRegNoContent struct {
}

// NewPostAuthRegNoContent creates PostAuthRegNoContent with default headers values
func NewPostAuthRegNoContent() *PostAuthRegNoContent {

	return &PostAuthRegNoContent{}
}

// WriteResponse to the client
func (o *PostAuthRegNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostAuthRegConflictCode is the HTTP code returned for type PostAuthRegConflict
const PostAuthRegConflictCode int = 409

/*PostAuthRegConflict User already present

swagger:response postAuthRegConflict
*/
type PostAuthRegConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthRegConflict creates PostAuthRegConflict with default headers values
func NewPostAuthRegConflict() *PostAuthRegConflict {

	return &PostAuthRegConflict{}
}

// WithPayload adds the payload to the post auth reg conflict response
func (o *PostAuthRegConflict) WithPayload(payload *models.Error) *PostAuthRegConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth reg conflict response
func (o *PostAuthRegConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthRegConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostAuthRegDefault Unexpected error

swagger:response postAuthRegDefault
*/
type PostAuthRegDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthRegDefault creates PostAuthRegDefault with default headers values
func NewPostAuthRegDefault(code int) *PostAuthRegDefault {
	if code <= 0 {
		code = 500
	}

	return &PostAuthRegDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post auth reg default response
func (o *PostAuthRegDefault) WithStatusCode(code int) *PostAuthRegDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post auth reg default response
func (o *PostAuthRegDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post auth reg default response
func (o *PostAuthRegDefault) WithPayload(payload *models.Error) *PostAuthRegDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth reg default response
func (o *PostAuthRegDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthRegDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
