// Code generated by go-swagger; DO NOT EDIT.

package references

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// GetReferencesOKCode is the HTTP code returned for type GetReferencesOK
const GetReferencesOKCode int = 200

/*GetReferencesOK ok

swagger:response getReferencesOK
*/
type GetReferencesOK struct {

	/*
	  In: Body
	*/
	Payload *models.AReferences `json:"body,omitempty"`
}

// NewGetReferencesOK creates GetReferencesOK with default headers values
func NewGetReferencesOK() *GetReferencesOK {

	return &GetReferencesOK{}
}

// WithPayload adds the payload to the get references o k response
func (o *GetReferencesOK) WithPayload(payload *models.AReferences) *GetReferencesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get references o k response
func (o *GetReferencesOK) SetPayload(payload *models.AReferences) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReferencesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetReferencesDefault Unexpected error

swagger:response getReferencesDefault
*/
type GetReferencesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReferencesDefault creates GetReferencesDefault with default headers values
func NewGetReferencesDefault(code int) *GetReferencesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetReferencesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get references default response
func (o *GetReferencesDefault) WithStatusCode(code int) *GetReferencesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get references default response
func (o *GetReferencesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get references default response
func (o *GetReferencesDefault) WithPayload(payload *models.Error) *GetReferencesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get references default response
func (o *GetReferencesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReferencesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
