// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetInviteByEmailTokenHandlerFunc turns a function with the right signature into a get invite by email token handler
type GetInviteByEmailTokenHandlerFunc func(GetInviteByEmailTokenParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInviteByEmailTokenHandlerFunc) Handle(params GetInviteByEmailTokenParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetInviteByEmailTokenHandler interface for that can handle valid get invite by email token params
type GetInviteByEmailTokenHandler interface {
	Handle(GetInviteByEmailTokenParams, interface{}) middleware.Responder
}

// NewGetInviteByEmailToken creates a new http.Handler for the get invite by email token operation
func NewGetInviteByEmailToken(ctx *middleware.Context, handler GetInviteByEmailTokenHandler) *GetInviteByEmailToken {
	return &GetInviteByEmailToken{Context: ctx, Handler: handler}
}

/*GetInviteByEmailToken swagger:route GET /invite/by-email/{token} Invites getInviteByEmailToken

GetInviteByEmailToken get invite by email token API

*/
type GetInviteByEmailToken struct {
	Context *middleware.Context
	Handler GetInviteByEmailTokenHandler
}

func (o *GetInviteByEmailToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetInviteByEmailTokenParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
