// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostInviteNewOKCode is the HTTP code returned for type PostInviteNewOK
const PostInviteNewOKCode int = 200

/*PostInviteNewOK email was send

swagger:response postInviteNewOK
*/
type PostInviteNewOK struct {

	/*
	  In: Body
	*/
	Payload *models.ACreateInvite `json:"body,omitempty"`
}

// NewPostInviteNewOK creates PostInviteNewOK with default headers values
func NewPostInviteNewOK() *PostInviteNewOK {

	return &PostInviteNewOK{}
}

// WithPayload adds the payload to the post invite new o k response
func (o *PostInviteNewOK) WithPayload(payload *models.ACreateInvite) *PostInviteNewOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invite new o k response
func (o *PostInviteNewOK) SetPayload(payload *models.ACreateInvite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInviteNewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInviteNewForbiddenCode is the HTTP code returned for type PostInviteNewForbidden
const PostInviteNewForbiddenCode int = 403

/*PostInviteNewForbidden access forbidden

swagger:response postInviteNewForbidden
*/
type PostInviteNewForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostInviteNewForbidden creates PostInviteNewForbidden with default headers values
func NewPostInviteNewForbidden() *PostInviteNewForbidden {

	return &PostInviteNewForbidden{}
}

// WithPayload adds the payload to the post invite new forbidden response
func (o *PostInviteNewForbidden) WithPayload(payload *models.Error) *PostInviteNewForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invite new forbidden response
func (o *PostInviteNewForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInviteNewForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInviteNewNotFoundCode is the HTTP code returned for type PostInviteNewNotFound
const PostInviteNewNotFoundCode int = 404

/*PostInviteNewNotFound cant find related entities

swagger:response postInviteNewNotFound
*/
type PostInviteNewNotFound struct {
}

// NewPostInviteNewNotFound creates PostInviteNewNotFound with default headers values
func NewPostInviteNewNotFound() *PostInviteNewNotFound {

	return &PostInviteNewNotFound{}
}

// WriteResponse to the client
func (o *PostInviteNewNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostInviteNewConflictCode is the HTTP code returned for type PostInviteNewConflict
const PostInviteNewConflictCode int = 409

/*PostInviteNewConflict this user has already been invited to this root

swagger:response postInviteNewConflict
*/
type PostInviteNewConflict struct {
}

// NewPostInviteNewConflict creates PostInviteNewConflict with default headers values
func NewPostInviteNewConflict() *PostInviteNewConflict {

	return &PostInviteNewConflict{}
}

// WriteResponse to the client
func (o *PostInviteNewConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

/*PostInviteNewDefault Unexpected error

swagger:response postInviteNewDefault
*/
type PostInviteNewDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostInviteNewDefault creates PostInviteNewDefault with default headers values
func NewPostInviteNewDefault(code int) *PostInviteNewDefault {
	if code <= 0 {
		code = 500
	}

	return &PostInviteNewDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post invite new default response
func (o *PostInviteNewDefault) WithStatusCode(code int) *PostInviteNewDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post invite new default response
func (o *PostInviteNewDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post invite new default response
func (o *PostInviteNewDefault) WithPayload(payload *models.Error) *PostInviteNewDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invite new default response
func (o *PostInviteNewDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInviteNewDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
