// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostInviteIDCancelNoContentCode is the HTTP code returned for type PostInviteIDCancelNoContent
const PostInviteIDCancelNoContentCode int = 204

/*PostInviteIDCancelNoContent the invite was canceled

swagger:response postInviteIdCancelNoContent
*/
type PostInviteIDCancelNoContent struct {
}

// NewPostInviteIDCancelNoContent creates PostInviteIDCancelNoContent with default headers values
func NewPostInviteIDCancelNoContent() *PostInviteIDCancelNoContent {

	return &PostInviteIDCancelNoContent{}
}

// WriteResponse to the client
func (o *PostInviteIDCancelNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostInviteIDCancelForbiddenCode is the HTTP code returned for type PostInviteIDCancelForbidden
const PostInviteIDCancelForbiddenCode int = 403

/*PostInviteIDCancelForbidden access forbidden

swagger:response postInviteIdCancelForbidden
*/
type PostInviteIDCancelForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostInviteIDCancelForbidden creates PostInviteIDCancelForbidden with default headers values
func NewPostInviteIDCancelForbidden() *PostInviteIDCancelForbidden {

	return &PostInviteIDCancelForbidden{}
}

// WithPayload adds the payload to the post invite Id cancel forbidden response
func (o *PostInviteIDCancelForbidden) WithPayload(payload *models.Error) *PostInviteIDCancelForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invite Id cancel forbidden response
func (o *PostInviteIDCancelForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInviteIDCancelForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostInviteIDCancelNotFoundCode is the HTTP code returned for type PostInviteIDCancelNotFound
const PostInviteIDCancelNotFoundCode int = 404

/*PostInviteIDCancelNotFound cant find invite

swagger:response postInviteIdCancelNotFound
*/
type PostInviteIDCancelNotFound struct {
}

// NewPostInviteIDCancelNotFound creates PostInviteIDCancelNotFound with default headers values
func NewPostInviteIDCancelNotFound() *PostInviteIDCancelNotFound {

	return &PostInviteIDCancelNotFound{}
}

// WriteResponse to the client
func (o *PostInviteIDCancelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostInviteIDCancelConflictCode is the HTTP code returned for type PostInviteIDCancelConflict
const PostInviteIDCancelConflictCode int = 409

/*PostInviteIDCancelConflict cant cancel invite

swagger:response postInviteIdCancelConflict
*/
type PostInviteIDCancelConflict struct {
}

// NewPostInviteIDCancelConflict creates PostInviteIDCancelConflict with default headers values
func NewPostInviteIDCancelConflict() *PostInviteIDCancelConflict {

	return &PostInviteIDCancelConflict{}
}

// WriteResponse to the client
func (o *PostInviteIDCancelConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

/*PostInviteIDCancelDefault Unexpected error

swagger:response postInviteIdCancelDefault
*/
type PostInviteIDCancelDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostInviteIDCancelDefault creates PostInviteIDCancelDefault with default headers values
func NewPostInviteIDCancelDefault(code int) *PostInviteIDCancelDefault {
	if code <= 0 {
		code = 500
	}

	return &PostInviteIDCancelDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post invite ID cancel default response
func (o *PostInviteIDCancelDefault) WithStatusCode(code int) *PostInviteIDCancelDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post invite ID cancel default response
func (o *PostInviteIDCancelDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post invite ID cancel default response
func (o *PostInviteIDCancelDefault) WithPayload(payload *models.Error) *PostInviteIDCancelDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invite ID cancel default response
func (o *PostInviteIDCancelDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInviteIDCancelDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
