// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostInviteByEmailNoContentCode is the HTTP code returned for type PostInviteByEmailNoContent
const PostInviteByEmailNoContentCode int = 204

/*PostInviteByEmailNoContent email was send

swagger:response postInviteByEmailNoContent
*/
type PostInviteByEmailNoContent struct {
}

// NewPostInviteByEmailNoContent creates PostInviteByEmailNoContent with default headers values
func NewPostInviteByEmailNoContent() *PostInviteByEmailNoContent {

	return &PostInviteByEmailNoContent{}
}

// WriteResponse to the client
func (o *PostInviteByEmailNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostInviteByEmailForbiddenCode is the HTTP code returned for type PostInviteByEmailForbidden
const PostInviteByEmailForbiddenCode int = 403

/*PostInviteByEmailForbidden access forbidden

swagger:response postInviteByEmailForbidden
*/
type PostInviteByEmailForbidden struct {
}

// NewPostInviteByEmailForbidden creates PostInviteByEmailForbidden with default headers values
func NewPostInviteByEmailForbidden() *PostInviteByEmailForbidden {

	return &PostInviteByEmailForbidden{}
}

// WriteResponse to the client
func (o *PostInviteByEmailForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostInviteByEmailNotFoundCode is the HTTP code returned for type PostInviteByEmailNotFound
const PostInviteByEmailNotFoundCode int = 404

/*PostInviteByEmailNotFound cant find related entities

swagger:response postInviteByEmailNotFound
*/
type PostInviteByEmailNotFound struct {
}

// NewPostInviteByEmailNotFound creates PostInviteByEmailNotFound with default headers values
func NewPostInviteByEmailNotFound() *PostInviteByEmailNotFound {

	return &PostInviteByEmailNotFound{}
}

// WriteResponse to the client
func (o *PostInviteByEmailNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostInviteByEmailConflictCode is the HTTP code returned for type PostInviteByEmailConflict
const PostInviteByEmailConflictCode int = 409

/*PostInviteByEmailConflict this user has already been invited to this root

swagger:response postInviteByEmailConflict
*/
type PostInviteByEmailConflict struct {
}

// NewPostInviteByEmailConflict creates PostInviteByEmailConflict with default headers values
func NewPostInviteByEmailConflict() *PostInviteByEmailConflict {

	return &PostInviteByEmailConflict{}
}

// WriteResponse to the client
func (o *PostInviteByEmailConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}

/*PostInviteByEmailDefault Unexpected error

swagger:response postInviteByEmailDefault
*/
type PostInviteByEmailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostInviteByEmailDefault creates PostInviteByEmailDefault with default headers values
func NewPostInviteByEmailDefault(code int) *PostInviteByEmailDefault {
	if code <= 0 {
		code = 500
	}

	return &PostInviteByEmailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post invite by email default response
func (o *PostInviteByEmailDefault) WithStatusCode(code int) *PostInviteByEmailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post invite by email default response
func (o *PostInviteByEmailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post invite by email default response
func (o *PostInviteByEmailDefault) WithPayload(payload *models.Error) *PostInviteByEmailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post invite by email default response
func (o *PostInviteByEmailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInviteByEmailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
