// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostInviteIDCancelHandlerFunc turns a function with the right signature into a post invite ID cancel handler
type PostInviteIDCancelHandlerFunc func(PostInviteIDCancelParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostInviteIDCancelHandlerFunc) Handle(params PostInviteIDCancelParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostInviteIDCancelHandler interface for that can handle valid post invite ID cancel params
type PostInviteIDCancelHandler interface {
	Handle(PostInviteIDCancelParams, interface{}) middleware.Responder
}

// NewPostInviteIDCancel creates a new http.Handler for the post invite ID cancel operation
func NewPostInviteIDCancel(ctx *middleware.Context, handler PostInviteIDCancelHandler) *PostInviteIDCancel {
	return &PostInviteIDCancel{Context: ctx, Handler: handler}
}

/*PostInviteIDCancel swagger:route POST /invite/{ID}/cancel Invites postInviteIdCancel

PostInviteIDCancel post invite ID cancel API

*/
type PostInviteIDCancel struct {
	Context *middleware.Context
	Handler PostInviteIDCancelHandler
}

func (o *PostInviteIDCancel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostInviteIDCancelParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
