// Code generated by go-swagger; DO NOT EDIT.

package invites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostInviteByEmailHandlerFunc turns a function with the right signature into a post invite by email handler
type PostInviteByEmailHandlerFunc func(PostInviteByEmailParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostInviteByEmailHandlerFunc) Handle(params PostInviteByEmailParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostInviteByEmailHandler interface for that can handle valid post invite by email params
type PostInviteByEmailHandler interface {
	Handle(PostInviteByEmailParams, interface{}) middleware.Responder
}

// NewPostInviteByEmail creates a new http.Handler for the post invite by email operation
func NewPostInviteByEmail(ctx *middleware.Context, handler PostInviteByEmailHandler) *PostInviteByEmail {
	return &PostInviteByEmail{Context: ctx, Handler: handler}
}

/*PostInviteByEmail swagger:route POST /invite/by-email Invites postInviteByEmail

PostInviteByEmail post invite by email API

*/
type PostInviteByEmail struct {
	Context *middleware.Context
	Handler PostInviteByEmailHandler
}

func (o *PostInviteByEmail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostInviteByEmailParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
