// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Collector API
Collector backend API


    Schemes:
      http
    Host: localhost:7000
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
