// Code generated by go-swagger; DO NOT EDIT.

package actors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteActorIDDeleteHandlerFunc turns a function with the right signature into a delete actor ID delete handler
type DeleteActorIDDeleteHandlerFunc func(DeleteActorIDDeleteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteActorIDDeleteHandlerFunc) Handle(params DeleteActorIDDeleteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteActorIDDeleteHandler interface for that can handle valid delete actor ID delete params
type DeleteActorIDDeleteHandler interface {
	Handle(DeleteActorIDDeleteParams, interface{}) middleware.Responder
}

// NewDeleteActorIDDelete creates a new http.Handler for the delete actor ID delete operation
func NewDeleteActorIDDelete(ctx *middleware.Context, handler DeleteActorIDDeleteHandler) *DeleteActorIDDelete {
	return &DeleteActorIDDelete{Context: ctx, Handler: handler}
}

/*DeleteActorIDDelete swagger:route DELETE /actor/{ID}/delete Actors deleteActorIdDelete

DeleteActorIDDelete delete actor ID delete API

*/
type DeleteActorIDDelete struct {
	Context *middleware.Context
	Handler DeleteActorIDDeleteHandler
}

func (o *DeleteActorIDDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteActorIDDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
