// Code generated by go-swagger; DO NOT EDIT.

package originlocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOriginLocationGetHandlerFunc turns a function with the right signature into a get origin location get handler
type GetOriginLocationGetHandlerFunc func(GetOriginLocationGetParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOriginLocationGetHandlerFunc) Handle(params GetOriginLocationGetParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetOriginLocationGetHandler interface for that can handle valid get origin location get params
type GetOriginLocationGetHandler interface {
	Handle(GetOriginLocationGetParams, interface{}) middleware.Responder
}

// NewGetOriginLocationGet creates a new http.Handler for the get origin location get operation
func NewGetOriginLocationGet(ctx *middleware.Context, handler GetOriginLocationGetHandler) *GetOriginLocationGet {
	return &GetOriginLocationGet{Context: ctx, Handler: handler}
}

/*GetOriginLocationGet swagger:route GET /origin-location/get Originlocations getOriginLocationGet

get origin locations

*/
type GetOriginLocationGet struct {
	Context *middleware.Context
	Handler GetOriginLocationGetHandler
}

func (o *GetOriginLocationGet) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOriginLocationGetParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
