// Code generated by go-swagger; DO NOT EDIT.

package originlocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "git.softndit.com/collector/backend/models"
)

// NewPostOriginLocationIDUpdateParams creates a new PostOriginLocationIDUpdateParams object
// no default values defined in spec.
func NewPostOriginLocationIDUpdateParams() PostOriginLocationIDUpdateParams {

	return PostOriginLocationIDUpdateParams{}
}

// PostOriginLocationIDUpdateParams contains all the bound params for the post origin location ID update operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostOriginLocationIDUpdate
type PostOriginLocationIDUpdateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ID int64
	/*
	  Required: true
	  In: body
	*/
	RUpdateOriginLocation *models.RUpdateOriginLocation
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostOriginLocationIDUpdateParams() beforehand.
func (o *PostOriginLocationIDUpdateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	var errInterface interface{}

	o.HTTPRequest = r

	rID, rhkID, _ := route.Params.GetOK("ID")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RUpdateOriginLocation
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("rUpdateOriginLocation", "body", errInterface))
			} else {
				res = append(res, errors.NewParseError("rUpdateOriginLocation", "body", "", err))
			}
		} else {

			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RUpdateOriginLocation = &body
			}
		}
	} else {
		res = append(res, errors.Required("rUpdateOriginLocation", "body", errInterface))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOriginLocationIDUpdateParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("ID", "path", "int64", raw)
	}
	o.ID = value

	return nil
}
