// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteTaskIDHandlerFunc turns a function with the right signature into a delete task ID handler
type DeleteTaskIDHandlerFunc func(DeleteTaskIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTaskIDHandlerFunc) Handle(params DeleteTaskIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteTaskIDHandler interface for that can handle valid delete task ID params
type DeleteTaskIDHandler interface {
	Handle(DeleteTaskIDParams, interface{}) middleware.Responder
}

// NewDeleteTaskID creates a new http.Handler for the delete task ID operation
func NewDeleteTaskID(ctx *middleware.Context, handler DeleteTaskIDHandler) *DeleteTaskID {
	return &DeleteTaskID{Context: ctx, Handler: handler}
}

/*DeleteTaskID swagger:route DELETE /task/{id} Tasks deleteTaskId

DeleteTaskID delete task ID API

*/
type DeleteTaskID struct {
	Context *middleware.Context
	Handler DeleteTaskIDHandler
}

func (o *DeleteTaskID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTaskIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
