// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTaskMyListHandlerFunc turns a function with the right signature into a get task my list handler
type GetTaskMyListHandlerFunc func(GetTaskMyListParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTaskMyListHandlerFunc) Handle(params GetTaskMyListParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTaskMyListHandler interface for that can handle valid get task my list params
type GetTaskMyListHandler interface {
	Handle(GetTaskMyListParams, interface{}) middleware.Responder
}

// NewGetTaskMyList creates a new http.Handler for the get task my list operation
func NewGetTaskMyList(ctx *middleware.Context, handler GetTaskMyListHandler) *GetTaskMyList {
	return &GetTaskMyList{Context: ctx, Handler: handler}
}

/*GetTaskMyList swagger:route GET /task/my-list Tasks getTaskMyList

GetTaskMyList get task my list API

*/
type GetTaskMyList struct {
	Context *middleware.Context
	Handler GetTaskMyListHandler
}

func (o *GetTaskMyList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTaskMyListParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
