// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTaskIDHandlerFunc turns a function with the right signature into a get task ID handler
type GetTaskIDHandlerFunc func(GetTaskIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTaskIDHandlerFunc) Handle(params GetTaskIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTaskIDHandler interface for that can handle valid get task ID params
type GetTaskIDHandler interface {
	Handle(GetTaskIDParams, interface{}) middleware.Responder
}

// NewGetTaskID creates a new http.Handler for the get task ID operation
func NewGetTaskID(ctx *middleware.Context, handler GetTaskIDHandler) *GetTaskID {
	return &GetTaskID{Context: ctx, Handler: handler}
}

/*GetTaskID swagger:route GET /task/{id} Tasks getTaskId

GetTaskID get task ID API

*/
type GetTaskID struct {
	Context *middleware.Context
	Handler GetTaskIDHandler
}

func (o *GetTaskID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTaskIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
