// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostTaskIDChangeStatusHandlerFunc turns a function with the right signature into a post task ID change status handler
type PostTaskIDChangeStatusHandlerFunc func(PostTaskIDChangeStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTaskIDChangeStatusHandlerFunc) Handle(params PostTaskIDChangeStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTaskIDChangeStatusHandler interface for that can handle valid post task ID change status params
type PostTaskIDChangeStatusHandler interface {
	Handle(PostTaskIDChangeStatusParams, interface{}) middleware.Responder
}

// NewPostTaskIDChangeStatus creates a new http.Handler for the post task ID change status operation
func NewPostTaskIDChangeStatus(ctx *middleware.Context, handler PostTaskIDChangeStatusHandler) *PostTaskIDChangeStatus {
	return &PostTaskIDChangeStatus{Context: ctx, Handler: handler}
}

/*PostTaskIDChangeStatus swagger:route POST /task/{id}/change-status Tasks postTaskIdChangeStatus

PostTaskIDChangeStatus post task ID change status API

*/
type PostTaskIDChangeStatus struct {
	Context *middleware.Context
	Handler PostTaskIDChangeStatusHandler
}

func (o *PostTaskIDChangeStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostTaskIDChangeStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
