// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutTaskIDHandlerFunc turns a function with the right signature into a put task ID handler
type PutTaskIDHandlerFunc func(PutTaskIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTaskIDHandlerFunc) Handle(params PutTaskIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutTaskIDHandler interface for that can handle valid put task ID params
type PutTaskIDHandler interface {
	Handle(PutTaskIDParams, interface{}) middleware.Responder
}

// NewPutTaskID creates a new http.Handler for the put task ID operation
func NewPutTaskID(ctx *middleware.Context, handler PutTaskIDHandler) *PutTaskID {
	return &PutTaskID{Context: ctx, Handler: handler}
}

/*PutTaskID swagger:route PUT /task/{id} Tasks putTaskId

PutTaskID put task ID API

*/
type PutTaskID struct {
	Context *middleware.Context
	Handler PutTaskIDHandler
}

func (o *PutTaskID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutTaskIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
