// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "git.softndit.com/collector/backend/models"
)

// PostSessionRegisterDeviceTokenNoContentCode is the HTTP code returned for type PostSessionRegisterDeviceTokenNoContent
const PostSessionRegisterDeviceTokenNoContentCode int = 204

/*PostSessionRegisterDeviceTokenNoContent success registred

swagger:response postSessionRegisterDeviceTokenNoContent
*/
type PostSessionRegisterDeviceTokenNoContent struct {
}

// NewPostSessionRegisterDeviceTokenNoContent creates PostSessionRegisterDeviceTokenNoContent with default headers values
func NewPostSessionRegisterDeviceTokenNoContent() *PostSessionRegisterDeviceTokenNoContent {

	return &PostSessionRegisterDeviceTokenNoContent{}
}

// WriteResponse to the client
func (o *PostSessionRegisterDeviceTokenNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*PostSessionRegisterDeviceTokenDefault Unexpected error

swagger:response postSessionRegisterDeviceTokenDefault
*/
type PostSessionRegisterDeviceTokenDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostSessionRegisterDeviceTokenDefault creates PostSessionRegisterDeviceTokenDefault with default headers values
func NewPostSessionRegisterDeviceTokenDefault(code int) *PostSessionRegisterDeviceTokenDefault {
	if code <= 0 {
		code = 500
	}

	return &PostSessionRegisterDeviceTokenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post session register device token default response
func (o *PostSessionRegisterDeviceTokenDefault) WithStatusCode(code int) *PostSessionRegisterDeviceTokenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post session register device token default response
func (o *PostSessionRegisterDeviceTokenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post session register device token default response
func (o *PostSessionRegisterDeviceTokenDefault) WithPayload(payload *models.Error) *PostSessionRegisterDeviceTokenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post session register device token default response
func (o *PostSessionRegisterDeviceTokenDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostSessionRegisterDeviceTokenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
