// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "git.softndit.com/collector/backend/models"
)

// NewPostMessageAllConversationParams creates a new PostMessageAllConversationParams object
// no default values defined in spec.
func NewPostMessageAllConversationParams() PostMessageAllConversationParams {

	return PostMessageAllConversationParams{}
}

// PostMessageAllConversationParams contains all the bound params for the post message all conversation operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostMessageAllConversation
type PostMessageAllConversationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	RGetAllConversation *models.RGetAllConversation
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostMessageAllConversationParams() beforehand.
func (o *PostMessageAllConversationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	var errInterface interface{}

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RGetAllConversation
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("rGetAllConversation", "body", errInterface))
			} else {
				res = append(res, errors.NewParseError("rGetAllConversation", "body", "", err))
			}
		} else {

			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RGetAllConversation = &body
			}
		}
	} else {
		res = append(res, errors.Required("rGetAllConversation", "body", errInterface))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
