// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostMessageRangeHandlerFunc turns a function with the right signature into a post message range handler
type PostMessageRangeHandlerFunc func(PostMessageRangeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMessageRangeHandlerFunc) Handle(params PostMessageRangeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostMessageRangeHandler interface for that can handle valid post message range params
type PostMessageRangeHandler interface {
	Handle(PostMessageRangeParams, interface{}) middleware.Responder
}

// NewPostMessageRange creates a new http.Handler for the post message range operation
func NewPostMessageRange(ctx *middleware.Context, handler PostMessageRangeHandler) *PostMessageRange {
	return &PostMessageRange{Context: ctx, Handler: handler}
}

/*PostMessageRange swagger:route POST /message/range Messages postMessageRange

Get messages line for peer

*/
type PostMessageRange struct {
	Context *middleware.Context
	Handler PostMessageRangeHandler
}

func (o *PostMessageRange) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMessageRangeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
