// Code generated by go-swagger; DO NOT EDIT.

package roots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRootByUserHandlerFunc turns a function with the right signature into a get root by user handler
type GetRootByUserHandlerFunc func(GetRootByUserParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRootByUserHandlerFunc) Handle(params GetRootByUserParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetRootByUserHandler interface for that can handle valid get root by user params
type GetRootByUserHandler interface {
	Handle(GetRootByUserParams, interface{}) middleware.Responder
}

// NewGetRootByUser creates a new http.Handler for the get root by user operation
func NewGetRootByUser(ctx *middleware.Context, handler GetRootByUserHandler) *GetRootByUser {
	return &GetRootByUser{Context: ctx, Handler: handler}
}

/*GetRootByUser swagger:route GET /root/by-user Roots getRootByUser

get users root

*/
type GetRootByUser struct {
	Context *middleware.Context
	Handler GetRootByUserHandler
}

func (o *GetRootByUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRootByUserParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
