// Code generated by go-swagger; DO NOT EDIT.

package roots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRootIDHandlerFunc turns a function with the right signature into a get root ID handler
type GetRootIDHandlerFunc func(GetRootIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRootIDHandlerFunc) Handle(params GetRootIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetRootIDHandler interface for that can handle valid get root ID params
type GetRootIDHandler interface {
	Handle(GetRootIDParams, interface{}) middleware.Responder
}

// NewGetRootID creates a new http.Handler for the get root ID operation
func NewGetRootID(ctx *middleware.Context, handler GetRootIDHandler) *GetRootID {
	return &GetRootID{Context: ctx, Handler: handler}
}

/*GetRootID swagger:route GET /root/{ID} Roots getRootId

get info about root

*/
type GetRootID struct {
	Context *middleware.Context
	Handler GetRootIDHandler
}

func (o *GetRootID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRootIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
