// Code generated by go-swagger; DO NOT EDIT.

package roots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostRootRemoveUserHandlerFunc turns a function with the right signature into a post root remove user handler
type PostRootRemoveUserHandlerFunc func(PostRootRemoveUserParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRootRemoveUserHandlerFunc) Handle(params PostRootRemoveUserParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostRootRemoveUserHandler interface for that can handle valid post root remove user params
type PostRootRemoveUserHandler interface {
	Handle(PostRootRemoveUserParams, interface{}) middleware.Responder
}

// NewPostRootRemoveUser creates a new http.Handler for the post root remove user operation
func NewPostRootRemoveUser(ctx *middleware.Context, handler PostRootRemoveUserHandler) *PostRootRemoveUser {
	return &PostRootRemoveUser{Context: ctx, Handler: handler}
}

/*PostRootRemoveUser swagger:route POST /root/remove-user Roots postRootRemoveUser

remove user from root

*/
type PostRootRemoveUser struct {
	Context *middleware.Context
	Handler PostRootRemoveUserHandler
}

func (o *PostRootRemoveUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostRootRemoveUserParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
