// !! Autogenerated file, do not edit!
package dto

import (
	"bytes"
	"errors"
	"fmt"

	"github.com/jackc/pgx"
)

// CollectionGroupRefField TBD
type CollectionGroupRefField int

const (
	// CollectionGroupRefFieldCollectionID TBD
	CollectionGroupRefFieldCollectionID CollectionGroupRefField = iota

	// CollectionGroupRefFieldGroupID TBD
	CollectionGroupRefFieldGroupID
)

// CollectionGroupRefFieldsList TBD
type CollectionGroupRefFieldsList []CollectionGroupRefField

// CollectionGroupRefAllFields TBD
var CollectionGroupRefAllFields = CollectionGroupRefFieldsList{
	CollectionGroupRefFieldCollectionID,
	CollectionGroupRefFieldGroupID,
}

// CollectionGroupRefFieldsNames TBD
var CollectionGroupRefFieldsNames = [...]string{
	"collection_id",
	"group_id",
}

// Name TBD
func (f CollectionGroupRefField) Name() string {
	if int(f) > len(CollectionGroupRefFieldsNames)-1 {
		return "unknown"
	}
	return CollectionGroupRefFieldsNames[f]
}

// JoinedNames TBD
func (l CollectionGroupRefFieldsList) JoinedNames() string {
	return l.JoinedNamesWithAlias("")
}

// JoinedNamesWithAlias TBD
func (l CollectionGroupRefFieldsList) JoinedNamesWithAlias(alias string) string {
	var aliasPrefix string
	if alias != "" {
		aliasPrefix = alias + "."
	}

	var buf bytes.Buffer
	for idx, f := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(aliasPrefix)
		buf.WriteString("\"")
		buf.WriteString(f.Name())
		buf.WriteString("\"")
	}
	return buf.String()
}

// Placeholders TBD
func (l CollectionGroupRefFieldsList) Placeholders() string {
	var buf bytes.Buffer
	for idx := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(fmt.Sprint("$", idx+1))
	}
	return buf.String()
}

// Del TBD
func (l CollectionGroupRefFieldsList) Del(fields ...CollectionGroupRefField) CollectionGroupRefFieldsList {
	var res = make(CollectionGroupRefFieldsList, 0, len(l))
	for _, srcFld := range l {
		remove := false
		for _, delFld := range fields {
			if srcFld == delFld {
				remove = true
				break
			}
		}
		if !remove {
			res = append(res, srcFld)
		}
	}
	return res
}

// PushBack TBD
func (l CollectionGroupRefFieldsList) PushBack(fields ...CollectionGroupRefField) CollectionGroupRefFieldsList {
	var res = make(CollectionGroupRefFieldsList, 0, len(l)+len(fields))
	for _, f := range l {
		res = append(res, f)
	}
	for _, f := range fields {
		res = append(res, f)
	}
	return res
}

// PushFront TBD
func (l CollectionGroupRefFieldsList) PushFront(fields ...CollectionGroupRefField) CollectionGroupRefFieldsList {
	var res = make(CollectionGroupRefFieldsList, 0, len(l)+len(fields))
	for _, f := range fields {
		res = append(res, f)
	}
	for _, f := range l {
		res = append(res, f)
	}
	return res
}

// FieldsValues TBD
func (x *CollectionGroupRef) FieldsValues(fields CollectionGroupRefFieldsList) []interface{} {
	values := make([]interface{}, 0, len(fields))
	for _, f := range fields {
		values = append(values, x.FieldValue(f))
	}
	return values
}

// FieldValue TBD
func (x *CollectionGroupRef) FieldValue(f CollectionGroupRefField) interface{} {
	switch f {
	case CollectionGroupRefFieldCollectionID:
		return x.CollectionID
	case CollectionGroupRefFieldGroupID:
		return x.GroupID
	}
	return nil
}

// SetFieldValue TBD
func (x *CollectionGroupRef) SetFieldValue(f CollectionGroupRefField, v interface{}) error {
	switch f {
	case CollectionGroupRefFieldCollectionID:
		x.CollectionID = v.(int64)
	case CollectionGroupRefFieldGroupID:
		x.GroupID = v.(int64)
	}
	return nil
}

// CollectionGroupRefQuerier TBD
type CollectionGroupRefQuerier interface {
	Query(sql string, args ...interface{}) (*pgx.Rows, error)
	QueryRow(sql string, args ...interface{}) *pgx.Row
	Exec(sql string, arguments ...interface{}) (commandTag pgx.CommandTag, err error)
}

// CollectionGroupRefRows TBD
type CollectionGroupRefRows struct {
	rows   *pgx.Rows
	fields CollectionGroupRefFieldsList
}

// Close TBD
func (r *CollectionGroupRefRows) Close() {
	if r.rows == nil {
		return
	}
	r.rows.Close()
}

// Next TBD
func (r *CollectionGroupRefRows) Next() bool {
	if r.rows == nil {
		return false
	}

	return r.rows.Next()
}

// Err TBD
func (r *CollectionGroupRefRows) Err() error {
	if r.rows == nil {
		return errors.New("empty rows")
	}
	return r.rows.Err()
}

// ScanTo TBD
func (r *CollectionGroupRefRows) ScanTo(x *CollectionGroupRef) error {
	values, err := r.rows.Values()
	if err != nil {
		return err
	}
	for idx, v := range values {
		if err := x.SetFieldValue(r.fields[idx], v); err != nil {
			return err
		}
	}

	return nil
}

// Scan TBD
func (r *CollectionGroupRefRows) Scan() (x *CollectionGroupRef, err error) {
	x = new(CollectionGroupRef)
	err = r.ScanTo(x)
	return
}

// ScanAll TBD
func (r *CollectionGroupRefRows) ScanAll(sizeHint int) ([]*CollectionGroupRef, error) {
	defer r.Close()

	if sizeHint == 0 {
		sizeHint = 10
	}

	var list = make([]*CollectionGroupRef, 0, sizeHint)

	for r.Next() {
		item, err := r.Scan()
		if err != nil {
			return list, err
		}
		list = append(list, item)
	}

	return list, r.Err()
}

// CollectionGroupRefRow TBD
type CollectionGroupRefRow CollectionGroupRefRows

// ScanTo TBD
func (r *CollectionGroupRefRow) ScanTo(x *CollectionGroupRef) error {
	rows := (*CollectionGroupRefRows)(r)
	defer rows.Close()

	if rows.Err() != nil {
		return rows.Err()
	}

	if !rows.Next() {
		if rows.Err() == nil {
			return pgx.ErrNoRows
		}
		return rows.Err()
	}

	return rows.ScanTo(x)
}

// Scan TBD
func (r *CollectionGroupRefRow) Scan() (x *CollectionGroupRef, err error) {
	x = new(CollectionGroupRef)
	err = r.ScanTo(x)
	return
}

// QueryCollectionGroupRef TBD
func QueryCollectionGroupRef(q CollectionGroupRefQuerier, fields CollectionGroupRefFieldsList, sql string, args ...interface{}) (*CollectionGroupRefRows, error) {
	pgxRows, err := q.Query(sql, args...)
	if err != nil {
		return nil, err
	}

	return &CollectionGroupRefRows{rows: pgxRows, fields: fields}, nil
}

// QueryCollectionGroupRefRow TBD
func QueryCollectionGroupRefRow(q CollectionGroupRefQuerier, fields CollectionGroupRefFieldsList, sql string, args ...interface{}) *CollectionGroupRefRow {
	pgxRows, _ := q.Query(sql, args...)
	return &CollectionGroupRefRow{rows: pgxRows, fields: fields}
}

// ScanCollectionGroupRefList TBD
func ScanCollectionGroupRefList(q CollectionGroupRefQuerier, fields CollectionGroupRefFieldsList, sql string, args ...interface{}) ([]*CollectionGroupRef, error) {
	rows, err := QueryCollectionGroupRef(q, fields, sql, args...)
	if err != nil {
		return nil, err
	}
	return rows.ScanAll(0)
}

// ScanCollectionGroupRef TBD
func ScanCollectionGroupRef(q CollectionGroupRefQuerier, fields CollectionGroupRefFieldsList, sql string, args ...interface{}) (*CollectionGroupRef, error) {
	x, err := QueryCollectionGroupRefRow(q, fields, sql, args...).Scan()
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	return x, err
}
