// !! Autogenerated file, do not edit!
package dto

import (
	"bytes"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx"
)

// DialogField TBD
type DialogField int

const (
	// DialogFieldID TBD
	DialogFieldID DialogField = iota

	// DialogFieldLeastUserID TBD
	DialogFieldLeastUserID

	// DialogFieldGreatestUserID TBD
	DialogFieldGreatestUserID

	// DialogFieldCreationTime TBD
	DialogFieldCreationTime
)

// DialogFieldsList TBD
type DialogFieldsList []DialogField

// DialogAllFields TBD
var DialogAllFields = DialogFieldsList{
	DialogFieldID,
	DialogFieldLeastUserID,
	DialogFieldGreatestUserID,
	DialogFieldCreationTime,
}

// DialogFieldsNames TBD
var DialogFieldsNames = [...]string{
	"id",
	"least_user_id",
	"greatest_user_id",
	"creation_time",
}

// Name TBD
func (f DialogField) Name() string {
	if int(f) > len(DialogFieldsNames)-1 {
		return "unknown"
	}
	return DialogFieldsNames[f]
}

// JoinedNames TBD
func (l DialogFieldsList) JoinedNames() string {
	return l.JoinedNamesWithAlias("")
}

// JoinedNamesWithAlias TBD
func (l DialogFieldsList) JoinedNamesWithAlias(alias string) string {
	var aliasPrefix string
	if alias != "" {
		aliasPrefix = alias + "."
	}

	var buf bytes.Buffer
	for idx, f := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(aliasPrefix)
		buf.WriteString("\"")
		buf.WriteString(f.Name())
		buf.WriteString("\"")
	}
	return buf.String()
}

// Placeholders TBD
func (l DialogFieldsList) Placeholders() string {
	var buf bytes.Buffer
	for idx := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(fmt.Sprint("$", idx+1))
	}
	return buf.String()
}

// Del TBD
func (l DialogFieldsList) Del(fields ...DialogField) DialogFieldsList {
	var res = make(DialogFieldsList, 0, len(l))
	for _, srcFld := range l {
		remove := false
		for _, delFld := range fields {
			if srcFld == delFld {
				remove = true
				break
			}
		}
		if !remove {
			res = append(res, srcFld)
		}
	}
	return res
}

// PushBack TBD
func (l DialogFieldsList) PushBack(fields ...DialogField) DialogFieldsList {
	var res = make(DialogFieldsList, 0, len(l)+len(fields))
	for _, f := range l {
		res = append(res, f)
	}
	for _, f := range fields {
		res = append(res, f)
	}
	return res
}

// PushFront TBD
func (l DialogFieldsList) PushFront(fields ...DialogField) DialogFieldsList {
	var res = make(DialogFieldsList, 0, len(l)+len(fields))
	for _, f := range fields {
		res = append(res, f)
	}
	for _, f := range l {
		res = append(res, f)
	}
	return res
}

// FieldsValues TBD
func (x *Dialog) FieldsValues(fields DialogFieldsList) []interface{} {
	values := make([]interface{}, 0, len(fields))
	for _, f := range fields {
		values = append(values, x.FieldValue(f))
	}
	return values
}

// FieldValue TBD
func (x *Dialog) FieldValue(f DialogField) interface{} {
	switch f {
	case DialogFieldID:
		return x.ID
	case DialogFieldLeastUserID:
		return x.LeastUserID
	case DialogFieldGreatestUserID:
		return x.GreatestUserID
	case DialogFieldCreationTime:
		return x.CreationTime
	}
	return nil
}

// SetFieldValue TBD
func (x *Dialog) SetFieldValue(f DialogField, v interface{}) error {
	switch f {
	case DialogFieldID:
		x.ID = v.(int64)
	case DialogFieldLeastUserID:
		x.LeastUserID = v.(int64)
	case DialogFieldGreatestUserID:
		x.GreatestUserID = v.(int64)
	case DialogFieldCreationTime:
		x.CreationTime = v.(time.Time)
	}
	return nil
}

// DialogQuerier TBD
type DialogQuerier interface {
	Query(sql string, args ...interface{}) (*pgx.Rows, error)
	QueryRow(sql string, args ...interface{}) *pgx.Row
	Exec(sql string, arguments ...interface{}) (commandTag pgx.CommandTag, err error)
}

// DialogRows TBD
type DialogRows struct {
	rows   *pgx.Rows
	fields DialogFieldsList
}

// Close TBD
func (r *DialogRows) Close() {
	if r.rows == nil {
		return
	}
	r.rows.Close()
}

// Next TBD
func (r *DialogRows) Next() bool {
	if r.rows == nil {
		return false
	}

	return r.rows.Next()
}

// Err TBD
func (r *DialogRows) Err() error {
	if r.rows == nil {
		return errors.New("empty rows")
	}
	return r.rows.Err()
}

// ScanTo TBD
func (r *DialogRows) ScanTo(x *Dialog) error {
	values, err := r.rows.Values()
	if err != nil {
		return err
	}
	for idx, v := range values {
		if err := x.SetFieldValue(r.fields[idx], v); err != nil {
			return err
		}
	}

	return nil
}

// Scan TBD
func (r *DialogRows) Scan() (x *Dialog, err error) {
	x = new(Dialog)
	err = r.ScanTo(x)
	return
}

// ScanAll TBD
func (r *DialogRows) ScanAll(sizeHint int) ([]*Dialog, error) {
	defer r.Close()

	if sizeHint == 0 {
		sizeHint = 10
	}

	var list = make([]*Dialog, 0, sizeHint)

	for r.Next() {
		item, err := r.Scan()
		if err != nil {
			return list, err
		}
		list = append(list, item)
	}

	return list, r.Err()
}

// DialogRow TBD
type DialogRow DialogRows

// ScanTo TBD
func (r *DialogRow) ScanTo(x *Dialog) error {
	rows := (*DialogRows)(r)
	defer rows.Close()

	if rows.Err() != nil {
		return rows.Err()
	}

	if !rows.Next() {
		if rows.Err() == nil {
			return pgx.ErrNoRows
		}
		return rows.Err()
	}

	return rows.ScanTo(x)
}

// Scan TBD
func (r *DialogRow) Scan() (x *Dialog, err error) {
	x = new(Dialog)
	err = r.ScanTo(x)
	return
}

// QueryDialog TBD
func QueryDialog(q DialogQuerier, fields DialogFieldsList, sql string, args ...interface{}) (*DialogRows, error) {
	pgxRows, err := q.Query(sql, args...)
	if err != nil {
		return nil, err
	}

	return &DialogRows{rows: pgxRows, fields: fields}, nil
}

// QueryDialogRow TBD
func QueryDialogRow(q DialogQuerier, fields DialogFieldsList, sql string, args ...interface{}) *DialogRow {
	pgxRows, _ := q.Query(sql, args...)
	return &DialogRow{rows: pgxRows, fields: fields}
}

// ScanDialogList TBD
func ScanDialogList(q DialogQuerier, fields DialogFieldsList, sql string, args ...interface{}) ([]*Dialog, error) {
	rows, err := QueryDialog(q, fields, sql, args...)
	if err != nil {
		return nil, err
	}
	return rows.ScanAll(0)
}

// ScanDialog TBD
func ScanDialog(q DialogQuerier, fields DialogFieldsList, sql string, args ...interface{}) (*Dialog, error) {
	x, err := QueryDialogRow(q, fields, sql, args...).Scan()
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	return x, err
}
