// !! Autogenerated file, do not edit!
package dto

import (
	"bytes"
	"errors"
	"fmt"

	"github.com/jackc/pgx"
)

// ObjectOriginLocationRefField TBD
type ObjectOriginLocationRefField int

const (
	// ObjectOriginLocationRefFieldObjectID TBD
	ObjectOriginLocationRefFieldObjectID ObjectOriginLocationRefField = iota

	// ObjectOriginLocationRefFieldOriginLocationID TBD
	ObjectOriginLocationRefFieldOriginLocationID
)

// ObjectOriginLocationRefFieldsList TBD
type ObjectOriginLocationRefFieldsList []ObjectOriginLocationRefField

// ObjectOriginLocationRefAllFields TBD
var ObjectOriginLocationRefAllFields = ObjectOriginLocationRefFieldsList{
	ObjectOriginLocationRefFieldObjectID,
	ObjectOriginLocationRefFieldOriginLocationID,
}

// ObjectOriginLocationRefFieldsNames TBD
var ObjectOriginLocationRefFieldsNames = [...]string{
	"object_id",
	"origin_location_id",
}

// Name TBD
func (f ObjectOriginLocationRefField) Name() string {
	if int(f) > len(ObjectOriginLocationRefFieldsNames)-1 {
		return "unknown"
	}
	return ObjectOriginLocationRefFieldsNames[f]
}

// JoinedNames TBD
func (l ObjectOriginLocationRefFieldsList) JoinedNames() string {
	return l.JoinedNamesWithAlias("")
}

// JoinedNamesWithAlias TBD
func (l ObjectOriginLocationRefFieldsList) JoinedNamesWithAlias(alias string) string {
	var aliasPrefix string
	if alias != "" {
		aliasPrefix = alias + "."
	}

	var buf bytes.Buffer
	for idx, f := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(aliasPrefix)
		buf.WriteString("\"")
		buf.WriteString(f.Name())
		buf.WriteString("\"")
	}
	return buf.String()
}

// Placeholders TBD
func (l ObjectOriginLocationRefFieldsList) Placeholders() string {
	var buf bytes.Buffer
	for idx := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(fmt.Sprint("$", idx+1))
	}
	return buf.String()
}

// Del TBD
func (l ObjectOriginLocationRefFieldsList) Del(fields ...ObjectOriginLocationRefField) ObjectOriginLocationRefFieldsList {
	var res = make(ObjectOriginLocationRefFieldsList, 0, len(l))
	for _, srcFld := range l {
		remove := false
		for _, delFld := range fields {
			if srcFld == delFld {
				remove = true
				break
			}
		}
		if !remove {
			res = append(res, srcFld)
		}
	}
	return res
}

// PushBack TBD
func (l ObjectOriginLocationRefFieldsList) PushBack(fields ...ObjectOriginLocationRefField) ObjectOriginLocationRefFieldsList {
	var res = make(ObjectOriginLocationRefFieldsList, 0, len(l)+len(fields))
	for _, f := range l {
		res = append(res, f)
	}
	for _, f := range fields {
		res = append(res, f)
	}
	return res
}

// PushFront TBD
func (l ObjectOriginLocationRefFieldsList) PushFront(fields ...ObjectOriginLocationRefField) ObjectOriginLocationRefFieldsList {
	var res = make(ObjectOriginLocationRefFieldsList, 0, len(l)+len(fields))
	for _, f := range fields {
		res = append(res, f)
	}
	for _, f := range l {
		res = append(res, f)
	}
	return res
}

// FieldsValues TBD
func (x *ObjectOriginLocationRef) FieldsValues(fields ObjectOriginLocationRefFieldsList) []interface{} {
	values := make([]interface{}, 0, len(fields))
	for _, f := range fields {
		values = append(values, x.FieldValue(f))
	}
	return values
}

// FieldValue TBD
func (x *ObjectOriginLocationRef) FieldValue(f ObjectOriginLocationRefField) interface{} {
	switch f {
	case ObjectOriginLocationRefFieldObjectID:
		return x.ObjectID
	case ObjectOriginLocationRefFieldOriginLocationID:
		return x.OriginLocationID
	}
	return nil
}

// SetFieldValue TBD
func (x *ObjectOriginLocationRef) SetFieldValue(f ObjectOriginLocationRefField, v interface{}) error {
	switch f {
	case ObjectOriginLocationRefFieldObjectID:
		x.ObjectID = v.(int64)
	case ObjectOriginLocationRefFieldOriginLocationID:
		x.OriginLocationID = v.(int64)
	}
	return nil
}

// ObjectOriginLocationRefQuerier TBD
type ObjectOriginLocationRefQuerier interface {
	Query(sql string, args ...interface{}) (*pgx.Rows, error)
	QueryRow(sql string, args ...interface{}) *pgx.Row
	Exec(sql string, arguments ...interface{}) (commandTag pgx.CommandTag, err error)
}

// ObjectOriginLocationRefRows TBD
type ObjectOriginLocationRefRows struct {
	rows   *pgx.Rows
	fields ObjectOriginLocationRefFieldsList
}

// Close TBD
func (r *ObjectOriginLocationRefRows) Close() {
	if r.rows == nil {
		return
	}
	r.rows.Close()
}

// Next TBD
func (r *ObjectOriginLocationRefRows) Next() bool {
	if r.rows == nil {
		return false
	}

	return r.rows.Next()
}

// Err TBD
func (r *ObjectOriginLocationRefRows) Err() error {
	if r.rows == nil {
		return errors.New("empty rows")
	}
	return r.rows.Err()
}

// ScanTo TBD
func (r *ObjectOriginLocationRefRows) ScanTo(x *ObjectOriginLocationRef) error {
	values, err := r.rows.Values()
	if err != nil {
		return err
	}
	for idx, v := range values {
		if err := x.SetFieldValue(r.fields[idx], v); err != nil {
			return err
		}
	}

	return nil
}

// Scan TBD
func (r *ObjectOriginLocationRefRows) Scan() (x *ObjectOriginLocationRef, err error) {
	x = new(ObjectOriginLocationRef)
	err = r.ScanTo(x)
	return
}

// ScanAll TBD
func (r *ObjectOriginLocationRefRows) ScanAll(sizeHint int) ([]*ObjectOriginLocationRef, error) {
	defer r.Close()

	if sizeHint == 0 {
		sizeHint = 10
	}

	var list = make([]*ObjectOriginLocationRef, 0, sizeHint)

	for r.Next() {
		item, err := r.Scan()
		if err != nil {
			return list, err
		}
		list = append(list, item)
	}

	return list, r.Err()
}

// ObjectOriginLocationRefRow TBD
type ObjectOriginLocationRefRow ObjectOriginLocationRefRows

// ScanTo TBD
func (r *ObjectOriginLocationRefRow) ScanTo(x *ObjectOriginLocationRef) error {
	rows := (*ObjectOriginLocationRefRows)(r)
	defer rows.Close()

	if rows.Err() != nil {
		return rows.Err()
	}

	if !rows.Next() {
		if rows.Err() == nil {
			return pgx.ErrNoRows
		}
		return rows.Err()
	}

	return rows.ScanTo(x)
}

// Scan TBD
func (r *ObjectOriginLocationRefRow) Scan() (x *ObjectOriginLocationRef, err error) {
	x = new(ObjectOriginLocationRef)
	err = r.ScanTo(x)
	return
}

// QueryObjectOriginLocationRef TBD
func QueryObjectOriginLocationRef(q ObjectOriginLocationRefQuerier, fields ObjectOriginLocationRefFieldsList, sql string, args ...interface{}) (*ObjectOriginLocationRefRows, error) {
	pgxRows, err := q.Query(sql, args...)
	if err != nil {
		return nil, err
	}

	return &ObjectOriginLocationRefRows{rows: pgxRows, fields: fields}, nil
}

// QueryObjectOriginLocationRefRow TBD
func QueryObjectOriginLocationRefRow(q ObjectOriginLocationRefQuerier, fields ObjectOriginLocationRefFieldsList, sql string, args ...interface{}) *ObjectOriginLocationRefRow {
	pgxRows, _ := q.Query(sql, args...)
	return &ObjectOriginLocationRefRow{rows: pgxRows, fields: fields}
}

// ScanObjectOriginLocationRefList TBD
func ScanObjectOriginLocationRefList(q ObjectOriginLocationRefQuerier, fields ObjectOriginLocationRefFieldsList, sql string, args ...interface{}) ([]*ObjectOriginLocationRef, error) {
	rows, err := QueryObjectOriginLocationRef(q, fields, sql, args...)
	if err != nil {
		return nil, err
	}
	return rows.ScanAll(0)
}

// ScanObjectOriginLocationRef TBD
func ScanObjectOriginLocationRef(q ObjectOriginLocationRefQuerier, fields ObjectOriginLocationRefFieldsList, sql string, args ...interface{}) (*ObjectOriginLocationRef, error) {
	x, err := QueryObjectOriginLocationRefRow(q, fields, sql, args...).Scan()
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	return x, err
}
