// !! Autogenerated file, do not edit!
package dto

import (
	"bytes"
	"errors"
	"fmt"

	"github.com/jackc/pgx"
)

// ObjectMaterialRefField TBD
type ObjectMaterialRefField int

const (
	// ObjectMaterialRefFieldObjectID TBD
	ObjectMaterialRefFieldObjectID ObjectMaterialRefField = iota

	// ObjectMaterialRefFieldMaterialID TBD
	ObjectMaterialRefFieldMaterialID
)

// ObjectMaterialRefFieldsList TBD
type ObjectMaterialRefFieldsList []ObjectMaterialRefField

// ObjectMaterialRefAllFields TBD
var ObjectMaterialRefAllFields = ObjectMaterialRefFieldsList{
	ObjectMaterialRefFieldObjectID,
	ObjectMaterialRefFieldMaterialID,
}

// ObjectMaterialRefFieldsNames TBD
var ObjectMaterialRefFieldsNames = [...]string{
	"object_id",
	"material_id",
}

// Name TBD
func (f ObjectMaterialRefField) Name() string {
	if int(f) > len(ObjectMaterialRefFieldsNames)-1 {
		return "unknown"
	}
	return ObjectMaterialRefFieldsNames[f]
}

// JoinedNames TBD
func (l ObjectMaterialRefFieldsList) JoinedNames() string {
	return l.JoinedNamesWithAlias("")
}

// JoinedNamesWithAlias TBD
func (l ObjectMaterialRefFieldsList) JoinedNamesWithAlias(alias string) string {
	var aliasPrefix string
	if alias != "" {
		aliasPrefix = alias + "."
	}

	var buf bytes.Buffer
	for idx, f := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(aliasPrefix)
		buf.WriteString("\"")
		buf.WriteString(f.Name())
		buf.WriteString("\"")
	}
	return buf.String()
}

// Placeholders TBD
func (l ObjectMaterialRefFieldsList) Placeholders() string {
	var buf bytes.Buffer
	for idx := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(fmt.Sprint("$", idx+1))
	}
	return buf.String()
}

// Del TBD
func (l ObjectMaterialRefFieldsList) Del(fields ...ObjectMaterialRefField) ObjectMaterialRefFieldsList {
	var res = make(ObjectMaterialRefFieldsList, 0, len(l))
	for _, srcFld := range l {
		remove := false
		for _, delFld := range fields {
			if srcFld == delFld {
				remove = true
				break
			}
		}
		if !remove {
			res = append(res, srcFld)
		}
	}
	return res
}

// PushBack TBD
func (l ObjectMaterialRefFieldsList) PushBack(fields ...ObjectMaterialRefField) ObjectMaterialRefFieldsList {
	var res = make(ObjectMaterialRefFieldsList, 0, len(l)+len(fields))
	for _, f := range l {
		res = append(res, f)
	}
	for _, f := range fields {
		res = append(res, f)
	}
	return res
}

// PushFront TBD
func (l ObjectMaterialRefFieldsList) PushFront(fields ...ObjectMaterialRefField) ObjectMaterialRefFieldsList {
	var res = make(ObjectMaterialRefFieldsList, 0, len(l)+len(fields))
	for _, f := range fields {
		res = append(res, f)
	}
	for _, f := range l {
		res = append(res, f)
	}
	return res
}

// FieldsValues TBD
func (x *ObjectMaterialRef) FieldsValues(fields ObjectMaterialRefFieldsList) []interface{} {
	values := make([]interface{}, 0, len(fields))
	for _, f := range fields {
		values = append(values, x.FieldValue(f))
	}
	return values
}

// FieldValue TBD
func (x *ObjectMaterialRef) FieldValue(f ObjectMaterialRefField) interface{} {
	switch f {
	case ObjectMaterialRefFieldObjectID:
		return x.ObjectID
	case ObjectMaterialRefFieldMaterialID:
		return x.MaterialID
	}
	return nil
}

// SetFieldValue TBD
func (x *ObjectMaterialRef) SetFieldValue(f ObjectMaterialRefField, v interface{}) error {
	switch f {
	case ObjectMaterialRefFieldObjectID:
		x.ObjectID = v.(int64)
	case ObjectMaterialRefFieldMaterialID:
		x.MaterialID = v.(int64)
	}
	return nil
}

// ObjectMaterialRefQuerier TBD
type ObjectMaterialRefQuerier interface {
	Query(sql string, args ...interface{}) (*pgx.Rows, error)
	QueryRow(sql string, args ...interface{}) *pgx.Row
	Exec(sql string, arguments ...interface{}) (commandTag pgx.CommandTag, err error)
}

// ObjectMaterialRefRows TBD
type ObjectMaterialRefRows struct {
	rows   *pgx.Rows
	fields ObjectMaterialRefFieldsList
}

// Close TBD
func (r *ObjectMaterialRefRows) Close() {
	if r.rows == nil {
		return
	}
	r.rows.Close()
}

// Next TBD
func (r *ObjectMaterialRefRows) Next() bool {
	if r.rows == nil {
		return false
	}

	return r.rows.Next()
}

// Err TBD
func (r *ObjectMaterialRefRows) Err() error {
	if r.rows == nil {
		return errors.New("empty rows")
	}
	return r.rows.Err()
}

// ScanTo TBD
func (r *ObjectMaterialRefRows) ScanTo(x *ObjectMaterialRef) error {
	values, err := r.rows.Values()
	if err != nil {
		return err
	}
	for idx, v := range values {
		if err := x.SetFieldValue(r.fields[idx], v); err != nil {
			return err
		}
	}

	return nil
}

// Scan TBD
func (r *ObjectMaterialRefRows) Scan() (x *ObjectMaterialRef, err error) {
	x = new(ObjectMaterialRef)
	err = r.ScanTo(x)
	return
}

// ScanAll TBD
func (r *ObjectMaterialRefRows) ScanAll(sizeHint int) ([]*ObjectMaterialRef, error) {
	defer r.Close()

	if sizeHint == 0 {
		sizeHint = 10
	}

	var list = make([]*ObjectMaterialRef, 0, sizeHint)

	for r.Next() {
		item, err := r.Scan()
		if err != nil {
			return list, err
		}
		list = append(list, item)
	}

	return list, r.Err()
}

// ObjectMaterialRefRow TBD
type ObjectMaterialRefRow ObjectMaterialRefRows

// ScanTo TBD
func (r *ObjectMaterialRefRow) ScanTo(x *ObjectMaterialRef) error {
	rows := (*ObjectMaterialRefRows)(r)
	defer rows.Close()

	if rows.Err() != nil {
		return rows.Err()
	}

	if !rows.Next() {
		if rows.Err() == nil {
			return pgx.ErrNoRows
		}
		return rows.Err()
	}

	return rows.ScanTo(x)
}

// Scan TBD
func (r *ObjectMaterialRefRow) Scan() (x *ObjectMaterialRef, err error) {
	x = new(ObjectMaterialRef)
	err = r.ScanTo(x)
	return
}

// QueryObjectMaterialRef TBD
func QueryObjectMaterialRef(q ObjectMaterialRefQuerier, fields ObjectMaterialRefFieldsList, sql string, args ...interface{}) (*ObjectMaterialRefRows, error) {
	pgxRows, err := q.Query(sql, args...)
	if err != nil {
		return nil, err
	}

	return &ObjectMaterialRefRows{rows: pgxRows, fields: fields}, nil
}

// QueryObjectMaterialRefRow TBD
func QueryObjectMaterialRefRow(q ObjectMaterialRefQuerier, fields ObjectMaterialRefFieldsList, sql string, args ...interface{}) *ObjectMaterialRefRow {
	pgxRows, _ := q.Query(sql, args...)
	return &ObjectMaterialRefRow{rows: pgxRows, fields: fields}
}

// ScanObjectMaterialRefList TBD
func ScanObjectMaterialRefList(q ObjectMaterialRefQuerier, fields ObjectMaterialRefFieldsList, sql string, args ...interface{}) ([]*ObjectMaterialRef, error) {
	rows, err := QueryObjectMaterialRef(q, fields, sql, args...)
	if err != nil {
		return nil, err
	}
	return rows.ScanAll(0)
}

// ScanObjectMaterialRef TBD
func ScanObjectMaterialRef(q ObjectMaterialRefQuerier, fields ObjectMaterialRefFieldsList, sql string, args ...interface{}) (*ObjectMaterialRef, error) {
	x, err := QueryObjectMaterialRefRow(q, fields, sql, args...).Scan()
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	return x, err
}
