// !! Autogenerated file, do not edit!
package dto

import (
	"bytes"
	"errors"
	"fmt"

	"github.com/jackc/pgx"
)

// TaskMediaRefField TBD
type TaskMediaRefField int

const (
	// TaskMediaRefFieldTaskID TBD
	TaskMediaRefFieldTaskID TaskMediaRefField = iota

	// TaskMediaRefFieldMediaID TBD
	TaskMediaRefFieldMediaID

	// TaskMediaRefFieldPosition TBD
	TaskMediaRefFieldPosition
)

// TaskMediaRefFieldsList TBD
type TaskMediaRefFieldsList []TaskMediaRefField

// TaskMediaRefAllFields TBD
var TaskMediaRefAllFields = TaskMediaRefFieldsList{
	TaskMediaRefFieldTaskID,
	TaskMediaRefFieldMediaID,
	TaskMediaRefFieldPosition,
}

// TaskMediaRefFieldsNames TBD
var TaskMediaRefFieldsNames = [...]string{
	"task_id",
	"media_id",
	"position",
}

// Name TBD
func (f TaskMediaRefField) Name() string {
	if int(f) > len(TaskMediaRefFieldsNames)-1 {
		return "unknown"
	}
	return TaskMediaRefFieldsNames[f]
}

// JoinedNames TBD
func (l TaskMediaRefFieldsList) JoinedNames() string {
	return l.JoinedNamesWithAlias("")
}

// JoinedNamesWithAlias TBD
func (l TaskMediaRefFieldsList) JoinedNamesWithAlias(alias string) string {
	var aliasPrefix string
	if alias != "" {
		aliasPrefix = alias + "."
	}

	var buf bytes.Buffer
	for idx, f := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(aliasPrefix)
		buf.WriteString("\"")
		buf.WriteString(f.Name())
		buf.WriteString("\"")
	}
	return buf.String()
}

// Placeholders TBD
func (l TaskMediaRefFieldsList) Placeholders() string {
	var buf bytes.Buffer
	for idx := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(fmt.Sprint("$", idx+1))
	}
	return buf.String()
}

// Del TBD
func (l TaskMediaRefFieldsList) Del(fields ...TaskMediaRefField) TaskMediaRefFieldsList {
	var res = make(TaskMediaRefFieldsList, 0, len(l))
	for _, srcFld := range l {
		remove := false
		for _, delFld := range fields {
			if srcFld == delFld {
				remove = true
				break
			}
		}
		if !remove {
			res = append(res, srcFld)
		}
	}
	return res
}

// PushBack TBD
func (l TaskMediaRefFieldsList) PushBack(fields ...TaskMediaRefField) TaskMediaRefFieldsList {
	var res = make(TaskMediaRefFieldsList, 0, len(l)+len(fields))
	for _, f := range l {
		res = append(res, f)
	}
	for _, f := range fields {
		res = append(res, f)
	}
	return res
}

// PushFront TBD
func (l TaskMediaRefFieldsList) PushFront(fields ...TaskMediaRefField) TaskMediaRefFieldsList {
	var res = make(TaskMediaRefFieldsList, 0, len(l)+len(fields))
	for _, f := range fields {
		res = append(res, f)
	}
	for _, f := range l {
		res = append(res, f)
	}
	return res
}

// FieldsValues TBD
func (x *TaskMediaRef) FieldsValues(fields TaskMediaRefFieldsList) []interface{} {
	values := make([]interface{}, 0, len(fields))
	for _, f := range fields {
		values = append(values, x.FieldValue(f))
	}
	return values
}

// FieldValue TBD
func (x *TaskMediaRef) FieldValue(f TaskMediaRefField) interface{} {
	switch f {
	case TaskMediaRefFieldTaskID:
		return x.TaskID
	case TaskMediaRefFieldMediaID:
		return x.MediaID
	case TaskMediaRefFieldPosition:
		return x.Position
	}
	return nil
}

// SetFieldValue TBD
func (x *TaskMediaRef) SetFieldValue(f TaskMediaRefField, v interface{}) error {
	switch f {
	case TaskMediaRefFieldTaskID:
		x.TaskID = v.(int64)
	case TaskMediaRefFieldMediaID:
		x.MediaID = v.(int64)
	case TaskMediaRefFieldPosition:
		x.Position = v.(int32)
	}
	return nil
}

// TaskMediaRefQuerier TBD
type TaskMediaRefQuerier interface {
	Query(sql string, args ...interface{}) (*pgx.Rows, error)
	QueryRow(sql string, args ...interface{}) *pgx.Row
	Exec(sql string, arguments ...interface{}) (commandTag pgx.CommandTag, err error)
}

// TaskMediaRefRows TBD
type TaskMediaRefRows struct {
	rows   *pgx.Rows
	fields TaskMediaRefFieldsList
}

// Close TBD
func (r *TaskMediaRefRows) Close() {
	if r.rows == nil {
		return
	}
	r.rows.Close()
}

// Next TBD
func (r *TaskMediaRefRows) Next() bool {
	if r.rows == nil {
		return false
	}

	return r.rows.Next()
}

// Err TBD
func (r *TaskMediaRefRows) Err() error {
	if r.rows == nil {
		return errors.New("empty rows")
	}
	return r.rows.Err()
}

// ScanTo TBD
func (r *TaskMediaRefRows) ScanTo(x *TaskMediaRef) error {
	values, err := r.rows.Values()
	if err != nil {
		return err
	}
	for idx, v := range values {
		if err := x.SetFieldValue(r.fields[idx], v); err != nil {
			return err
		}
	}

	return nil
}

// Scan TBD
func (r *TaskMediaRefRows) Scan() (x *TaskMediaRef, err error) {
	x = new(TaskMediaRef)
	err = r.ScanTo(x)
	return
}

// ScanAll TBD
func (r *TaskMediaRefRows) ScanAll(sizeHint int) ([]*TaskMediaRef, error) {
	defer r.Close()

	if sizeHint == 0 {
		sizeHint = 10
	}

	var list = make([]*TaskMediaRef, 0, sizeHint)

	for r.Next() {
		item, err := r.Scan()
		if err != nil {
			return list, err
		}
		list = append(list, item)
	}

	return list, r.Err()
}

// TaskMediaRefRow TBD
type TaskMediaRefRow TaskMediaRefRows

// ScanTo TBD
func (r *TaskMediaRefRow) ScanTo(x *TaskMediaRef) error {
	rows := (*TaskMediaRefRows)(r)
	defer rows.Close()

	if rows.Err() != nil {
		return rows.Err()
	}

	if !rows.Next() {
		if rows.Err() == nil {
			return pgx.ErrNoRows
		}
		return rows.Err()
	}

	return rows.ScanTo(x)
}

// Scan TBD
func (r *TaskMediaRefRow) Scan() (x *TaskMediaRef, err error) {
	x = new(TaskMediaRef)
	err = r.ScanTo(x)
	return
}

// QueryTaskMediaRef TBD
func QueryTaskMediaRef(q TaskMediaRefQuerier, fields TaskMediaRefFieldsList, sql string, args ...interface{}) (*TaskMediaRefRows, error) {
	pgxRows, err := q.Query(sql, args...)
	if err != nil {
		return nil, err
	}

	return &TaskMediaRefRows{rows: pgxRows, fields: fields}, nil
}

// QueryTaskMediaRefRow TBD
func QueryTaskMediaRefRow(q TaskMediaRefQuerier, fields TaskMediaRefFieldsList, sql string, args ...interface{}) *TaskMediaRefRow {
	pgxRows, _ := q.Query(sql, args...)
	return &TaskMediaRefRow{rows: pgxRows, fields: fields}
}

// ScanTaskMediaRefList TBD
func ScanTaskMediaRefList(q TaskMediaRefQuerier, fields TaskMediaRefFieldsList, sql string, args ...interface{}) ([]*TaskMediaRef, error) {
	rows, err := QueryTaskMediaRef(q, fields, sql, args...)
	if err != nil {
		return nil, err
	}
	return rows.ScanAll(0)
}

// ScanTaskMediaRef TBD
func ScanTaskMediaRef(q TaskMediaRefQuerier, fields TaskMediaRefFieldsList, sql string, args ...interface{}) (*TaskMediaRef, error) {
	x, err := QueryTaskMediaRefRow(q, fields, sql, args...).Scan()
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	return x, err
}
