// !! Autogenerated file, do not edit!
package dto

import (
	"bytes"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx"
)

// UserBanField TBD
type UserBanField int

const (
	// UserBanFieldID TBD
	UserBanFieldID UserBanField = iota

	// UserBanFieldCreatorUserID TBD
	UserBanFieldCreatorUserID

	// UserBanFieldUserID TBD
	UserBanFieldUserID

	// UserBanFieldCreationTime TBD
	UserBanFieldCreationTime
)

// UserBanFieldsList TBD
type UserBanFieldsList []UserBanField

// UserBanAllFields TBD
var UserBanAllFields = UserBanFieldsList{
	UserBanFieldID,
	UserBanFieldCreatorUserID,
	UserBanFieldUserID,
	UserBanFieldCreationTime,
}

// UserBanFieldsNames TBD
var UserBanFieldsNames = [...]string{
	"id",
	"creator_user_id",
	"user_id",
	"creation_time",
}

// Name TBD
func (f UserBanField) Name() string {
	if int(f) > len(UserBanFieldsNames)-1 {
		return "unknown"
	}
	return UserBanFieldsNames[f]
}

// JoinedNames TBD
func (l UserBanFieldsList) JoinedNames() string {
	return l.JoinedNamesWithAlias("")
}

// JoinedNamesWithAlias TBD
func (l UserBanFieldsList) JoinedNamesWithAlias(alias string) string {
	var aliasPrefix string
	if alias != "" {
		aliasPrefix = alias + "."
	}

	var buf bytes.Buffer
	for idx, f := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(aliasPrefix)
		buf.WriteString("\"")
		buf.WriteString(f.Name())
		buf.WriteString("\"")
	}
	return buf.String()
}

// Placeholders TBD
func (l UserBanFieldsList) Placeholders() string {
	var buf bytes.Buffer
	for idx := range l {
		if idx != 0 {
			buf.WriteString(",")
		}
		buf.WriteString(fmt.Sprint("$", idx+1))
	}
	return buf.String()
}

// Del TBD
func (l UserBanFieldsList) Del(fields ...UserBanField) UserBanFieldsList {
	var res = make(UserBanFieldsList, 0, len(l))
	for _, srcFld := range l {
		remove := false
		for _, delFld := range fields {
			if srcFld == delFld {
				remove = true
				break
			}
		}
		if !remove {
			res = append(res, srcFld)
		}
	}
	return res
}

// PushBack TBD
func (l UserBanFieldsList) PushBack(fields ...UserBanField) UserBanFieldsList {
	var res = make(UserBanFieldsList, 0, len(l)+len(fields))
	for _, f := range l {
		res = append(res, f)
	}
	for _, f := range fields {
		res = append(res, f)
	}
	return res
}

// PushFront TBD
func (l UserBanFieldsList) PushFront(fields ...UserBanField) UserBanFieldsList {
	var res = make(UserBanFieldsList, 0, len(l)+len(fields))
	for _, f := range fields {
		res = append(res, f)
	}
	for _, f := range l {
		res = append(res, f)
	}
	return res
}

// FieldsValues TBD
func (x *UserBan) FieldsValues(fields UserBanFieldsList) []interface{} {
	values := make([]interface{}, 0, len(fields))
	for _, f := range fields {
		values = append(values, x.FieldValue(f))
	}
	return values
}

// FieldValue TBD
func (x *UserBan) FieldValue(f UserBanField) interface{} {
	switch f {
	case UserBanFieldID:
		return x.ID
	case UserBanFieldCreatorUserID:
		return x.CreatorUserID
	case UserBanFieldUserID:
		return x.UserID
	case UserBanFieldCreationTime:
		return &x.CreationTime
	}
	return nil
}

// SetFieldValue TBD
func (x *UserBan) SetFieldValue(f UserBanField, v interface{}) error {
	switch f {
	case UserBanFieldID:
		x.ID = v.(int64)
	case UserBanFieldCreatorUserID:
		x.CreatorUserID = v.(int64)
	case UserBanFieldUserID:
		x.UserID = v.(int64)
	case UserBanFieldCreationTime:
		if v == nil {
			x.CreationTime = nil
		} else {
			value := v.(time.Time)
			x.CreationTime = &value
		}
	}
	return nil
}

// UserBanQuerier TBD
type UserBanQuerier interface {
	Query(sql string, args ...interface{}) (*pgx.Rows, error)
	QueryRow(sql string, args ...interface{}) *pgx.Row
	Exec(sql string, arguments ...interface{}) (commandTag pgx.CommandTag, err error)
}

// UserBanRows TBD
type UserBanRows struct {
	rows   *pgx.Rows
	fields UserBanFieldsList
}

// Close TBD
func (r *UserBanRows) Close() {
	if r.rows == nil {
		return
	}
	r.rows.Close()
}

// Next TBD
func (r *UserBanRows) Next() bool {
	if r.rows == nil {
		return false
	}

	return r.rows.Next()
}

// Err TBD
func (r *UserBanRows) Err() error {
	if r.rows == nil {
		return errors.New("empty rows")
	}
	return r.rows.Err()
}

// ScanTo TBD
func (r *UserBanRows) ScanTo(x *UserBan) error {
	values, err := r.rows.Values()
	if err != nil {
		return err
	}
	for idx, v := range values {
		if err := x.SetFieldValue(r.fields[idx], v); err != nil {
			return err
		}
	}

	return nil
}

// Scan TBD
func (r *UserBanRows) Scan() (x *UserBan, err error) {
	x = new(UserBan)
	err = r.ScanTo(x)
	return
}

// ScanAll TBD
func (r *UserBanRows) ScanAll(sizeHint int) ([]*UserBan, error) {
	defer r.Close()

	if sizeHint == 0 {
		sizeHint = 10
	}

	var list = make([]*UserBan, 0, sizeHint)

	for r.Next() {
		item, err := r.Scan()
		if err != nil {
			return list, err
		}
		list = append(list, item)
	}

	return list, r.Err()
}

// UserBanRow TBD
type UserBanRow UserBanRows

// ScanTo TBD
func (r *UserBanRow) ScanTo(x *UserBan) error {
	rows := (*UserBanRows)(r)
	defer rows.Close()

	if rows.Err() != nil {
		return rows.Err()
	}

	if !rows.Next() {
		if rows.Err() == nil {
			return pgx.ErrNoRows
		}
		return rows.Err()
	}

	return rows.ScanTo(x)
}

// Scan TBD
func (r *UserBanRow) Scan() (x *UserBan, err error) {
	x = new(UserBan)
	err = r.ScanTo(x)
	return
}

// QueryUserBan TBD
func QueryUserBan(q UserBanQuerier, fields UserBanFieldsList, sql string, args ...interface{}) (*UserBanRows, error) {
	pgxRows, err := q.Query(sql, args...)
	if err != nil {
		return nil, err
	}

	return &UserBanRows{rows: pgxRows, fields: fields}, nil
}

// QueryUserBanRow TBD
func QueryUserBanRow(q UserBanQuerier, fields UserBanFieldsList, sql string, args ...interface{}) *UserBanRow {
	pgxRows, _ := q.Query(sql, args...)
	return &UserBanRow{rows: pgxRows, fields: fields}
}

// ScanUserBanList TBD
func ScanUserBanList(q UserBanQuerier, fields UserBanFieldsList, sql string, args ...interface{}) ([]*UserBan, error) {
	rows, err := QueryUserBan(q, fields, sql, args...)
	if err != nil {
		return nil, err
	}
	return rows.ScanAll(0)
}

// ScanUserBan TBD
func ScanUserBan(q UserBanQuerier, fields UserBanFieldsList, sql string, args ...interface{}) (*UserBan, error) {
	x, err := QueryUserBanRow(q, fields, sql, args...).Scan()
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	return x, err
}
